"""Auto Issue Fix orchestration primitives.

Auto Issue Fix is a governed workflow layer for turning GitHub issues into auditable
candidate fixes. It supports safe previews and live draft PR execution while
keeping public PR text maintainer-facing and local evidence auditable.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
import time
from dataclasses import asdict
from dataclasses import dataclass
from dataclasses import field
from pathlib import Path


AUTO_ISSUE_FIX_MODES = ("review-gated", "draft-auto")
AUTO_REVIEW_MODES = ("required",)
AUTO_REVIEW_VERDICTS = ("pass", "needs_fix", "block")
AUTO_REVIEW_STAGES = (
    ("task", "任务审查", "确认仓库、issue、目标、边界和风险。"),
    ("plan", "计划审查", "检查执行计划、写入范围、测试策略和失败回退。"),
    ("context", "上下文审查", "确认必要文件和 issue 背景已经进入后续执行上下文。"),
    ("diff", "Diff 审查", "检查是否存在无关改动、生成物污染或大范围重写。"),
    ("tests", "测试审查", "检查 baseline、修复后测试和失败日志是否匹配 issue。"),
    ("security", "安全审查", "检查 secret、路径泄露、危险命令、越权写入和供应链风险。"),
    ("pr-readiness", "PR 准备审查", "检查 PR 描述、证据包、变更摘要、测试命令和风险说明。"),
)
PUBLIC_PR_BODY_FORBIDDEN_TERMS = (
    "AI",
    "RepoHarness",
    "repo-harness",
    "MiMo",
    "experiment",
    "model",
    "trace",
    "benchmark",
    "dogfood",
    "generated by",
)
GITHUB_BLOCKED_ERROR_PATTERNS = (
    "blocked from",
    "you have been blocked",
    "cannot perform this action",
    "permission denied",
    "forbidden",
    "resource not accessible",
)
SECRET_PATTERNS = (
    re.compile(r"\b(?:sk|gho|ghp|github_pat)[_-][A-Za-z0-9_=-]{6,}"),
    re.compile(r"\b(?:OPENAI_API_KEY|GITHUB_TOKEN|GH_TOKEN|MIMO_API_KEY|COOKIE|cookie)\s*=\s*[^\s]+", re.I),
    re.compile(r"\b(?:token|api[_-]?key|cookie)\s*[:=]\s*[^\s]+", re.I),
)


@dataclass(frozen=True)
class AutoIssueFixConfig:
    repo: str = ""
    issue: int | None = None
    discover: bool = False
    source: str = "trending"
    criteria: tuple[str, ...] = ("bug", "test")
    mode: str = "review-gated"
    evidence_dir: Path | None = None
    workspace_root: Path | None = None
    dry_run: bool = False
    include_local_paths: bool = False
    test_commands: tuple[str, ...] = ()
    auto_review: str = "required"
    max_review_repairs: int = 2
    resume: str = ""
    workdir: Path | None = None
    provider: str = "openai"
    model: str | None = None
    base_url: str | None = None
    host: str | None = None
    temperature: float = 0.2
    top_p: float = 0.9
    ollama_timeout: int = 300
    openai_timeout: int = 300
    max_steps: int = 50
    max_new_tokens: int = 8192
    commit_message: str = ""

    def validate(self) -> None:
        if self.mode not in AUTO_ISSUE_FIX_MODES:
            raise ValueError(f"mode must be one of: {', '.join(AUTO_ISSUE_FIX_MODES)}")
        if self.auto_review not in AUTO_REVIEW_MODES:
            raise ValueError("auto-review must be required")
        if self.mode == "draft-auto" and self.auto_review != "required":
            raise ValueError("draft-auto cannot disable automatic review gates")
        if self.max_review_repairs < 0:
            raise ValueError("--max-review-repairs must be zero or greater")
        if self.max_steps <= 0:
            raise ValueError("--max-steps must be greater than zero")
        if self.max_new_tokens <= 0:
            raise ValueError("--max-new-tokens must be greater than zero")
        if not self.discover and (not self.repo or self.issue is None):
            raise ValueError("auto-issue-fix requires --repo and --issue unless --discover is set")
        if self.discover and self.repo and self.issue is not None:
            raise ValueError("--discover cannot be combined with both --repo and --issue")

    def risk_notice(self) -> str:
        if self.mode == "draft-auto":
            return (
                "draft-auto skips human pauses only after automatic review gates pass. "
                "A block verdict stops the run and writes fallback evidence instead of creating a draft PR."
            )
        return (
            "review-gated uses the same automatic review gates, then pauses for human confirmation "
            "at high-risk checkpoints."
        )


@dataclass(frozen=True)
class AutoIssueFixReviewGate:
    stage: str
    title: str
    verdict: str
    summary: str
    required_action: str = ""
    repair_attempts: int = 0

    def validate(self) -> None:
        if self.verdict not in AUTO_REVIEW_VERDICTS:
            raise ValueError(f"review verdict must be one of: {', '.join(AUTO_REVIEW_VERDICTS)}")


@dataclass(frozen=True)
class AutoIssueFixRunRecord:
    run_id: str
    mode: str
    repo: str
    issue: int | None
    workspace_path: str
    evidence_dir: str
    status: str
    summary: str
    tests: list[dict]
    pr_url: str = ""
    fallback_reason: str = ""
    selected_issue_url: str = ""
    changed_paths: tuple[str, ...] = ()
    auto_review: str = "required"
    max_review_repairs: int = 2
    review_gates: tuple[AutoIssueFixReviewGate, ...] = ()
    resume_from: str = ""
    stage: str = ""
    branch: str = ""
    commit: str = ""
    baseline_status: str = ""
    workdir: str = ""


@dataclass(frozen=True)
class CommandResult:
    args: tuple[str, ...]
    cwd: str
    returncode: int
    stdout: str
    stderr: str

    @property
    def ok(self) -> bool:
        return self.returncode == 0

    def combined(self) -> str:
        return (self.stdout + "\n" + self.stderr).strip()


@dataclass(frozen=True)
class AutoIssueFixIssue:
    repo: str
    number: int
    title: str
    body: str = ""
    url: str = ""
    labels: tuple[str, ...] = ()
    state: str = "open"
    assignees: tuple[str, ...] = ()

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class LiveRunContext:
    config: AutoIssueFixConfig
    run_id: str
    workspace_root: Path
    evidence_dir: Path
    workdir: Path
    issue: AutoIssueFixIssue | None = None
    branch: str = ""
    pr_url: str = ""
    commit: str = ""
    changed_paths: list[str] = field(default_factory=list)
    tests: list[dict] = field(default_factory=list)
    review_gates: list[AutoIssueFixReviewGate] = field(default_factory=list)
    fallback_reason: str = ""
    stage: str = "initialized"
    baseline_status: str = ""


class GhCliBackend:
    def __init__(self, runner=None):
        self.runner = runner or run_command

    def issue_view(self, repo: str, issue: int) -> AutoIssueFixIssue:
        result = self.runner(
            [
                "gh",
                "issue",
                "view",
                str(issue),
                "--repo",
                normalize_repo(repo),
                "--json",
                "number,title,body,url,labels,state,assignees",
            ]
        )
        require_ok(result, "gh issue view failed")
        payload = json.loads(result.stdout or "{}")
        return issue_from_gh_payload(normalize_repo(repo), payload)

    def issue_list(self, repo: str, limit: int = 20) -> list[AutoIssueFixIssue]:
        result = self.runner(
            [
                "gh",
                "issue",
                "list",
                "--repo",
                normalize_repo(repo),
                "--state",
                "open",
                "--limit",
                str(limit),
                "--json",
                "number,title,body,url,labels,state,assignees",
            ]
        )
        require_ok(result, "gh issue list failed")
        return [issue_from_gh_payload(normalize_repo(repo), item) for item in json.loads(result.stdout or "[]")]

    def search_repos(self, query: str = "topic:python sort:stars-desc", limit: int = 10) -> list[str]:
        result = self.runner(
            ["gh", "search", "repos", query, "--limit", str(limit), "--json", "fullName"]
        )
        require_ok(result, "gh search repos failed")
        return [str(item.get("fullName", "")).strip() for item in json.loads(result.stdout or "[]") if item.get("fullName")]

    def default_branch(self, repo: str) -> str:
        result = self.runner(["gh", "repo", "view", normalize_repo(repo), "--json", "defaultBranchRef"])
        require_ok(result, "gh repo view failed")
        payload = json.loads(result.stdout or "{}")
        return str((payload.get("defaultBranchRef") or {}).get("name") or "main")

    def clone(self, repo: str, destination: Path) -> None:
        result = self.runner(["gh", "repo", "clone", normalize_repo(repo), str(destination)])
        require_ok(result, "gh repo clone failed")

    def ensure_fork_remote(self, cwd: Path) -> None:
        result = self.runner(
            ["gh", "repo", "fork", "--remote", "--remote-name", "fork", "--clone=false"],
            cwd=cwd,
        )
        if result.ok:
            return
        remotes = run_command(["git", "remote"], cwd=cwd)
        if "fork" in remotes.stdout.split():
            return
        require_ok(result, "gh repo fork failed")

    def current_user(self) -> str:
        result = self.runner(["gh", "api", "user", "--jq", ".login"])
        require_ok(result, "gh api user failed")
        return result.stdout.strip()

    def create_pr(self, repo: str, branch: str, title: str, body_file: Path, base: str) -> str:
        user = self.current_user()
        result = self.runner(
            [
                "gh",
                "pr",
                "create",
                "--repo",
                normalize_repo(repo),
                "--head",
                f"{user}:{branch}",
                "--base",
                base,
                "--title",
                title,
                "--body-file",
                str(body_file),
                "--draft",
            ]
        )
        require_ok(result, "gh pr create failed")
        return result.stdout.strip().splitlines()[-1].strip()


def redact_text(text: str) -> str:
    redacted = str(text)
    for pattern in SECRET_PATTERNS:
        redacted = pattern.sub("<redacted>", redacted)
    return redacted


def classify_github_error(text: str) -> str:
    lowered = str(text or "").lower()
    if any(pattern in lowered for pattern in GITHUB_BLOCKED_ERROR_PATTERNS):
        return "blocked_or_forbidden"
    return ""


def _contains_public_forbidden_term(text: str, term: str) -> bool:
    if " " in term or "-" in term:
        return term.lower() in text.lower()
    return re.search(rf"\b{re.escape(term)}\b", text, re.IGNORECASE) is not None


def maintainer_trust_block_reason(*, title: str, body: str, commit_message: str, branch: str) -> str:
    fields = {
        "title": title,
        "body": body,
        "commit message": commit_message,
        "branch": branch,
    }
    for field_name, value in fields.items():
        # Product naming will be revisited in a later rename pass. For now, keep
        # the existing internal branch prefix from blocking otherwise clean PRs.
        if field_name == "branch" and re.fullmatch(r"repo-harness-auto-issue-fix-\d+", str(value or "")):
            continue
        for term in PUBLIC_PR_BODY_FORBIDDEN_TERMS:
            if _contains_public_forbidden_term(str(value or ""), term):
                return f"maintainer trust gate blocked public {field_name} term: {term}"
    return ""


def normalize_repo(repo: str) -> str:
    value = str(repo or "").strip().removesuffix(".git").rstrip("/")
    if value.startswith("https://github.com/"):
        value = value[len("https://github.com/") :]
    if value.startswith("http://github.com/"):
        value = value[len("http://github.com/") :]
    if value.startswith("git@github.com:"):
        value = value[len("git@github.com:") :]
    return value


def run_command(args, cwd: Path | str | None = None, timeout: int = 300) -> CommandResult:
    cwd_text = str(Path(cwd).resolve()) if cwd else ""
    completed = subprocess.run(
        [str(item) for item in args],
        cwd=str(cwd) if cwd else None,
        text=True,
        capture_output=True,
        timeout=timeout,
        check=False,
    )
    return CommandResult(
        args=tuple(str(item) for item in args),
        cwd=cwd_text,
        returncode=int(completed.returncode),
        stdout=completed.stdout or "",
        stderr=completed.stderr or "",
    )


def require_ok(result: CommandResult, message: str) -> None:
    if result.ok:
        return
    command = " ".join(result.args)
    classification = classify_github_error(result.combined())
    if classification:
        raise RuntimeError(
            f"{message}: GitHub returned {classification}. "
            "Stop without retrying or bypassing; write fallback evidence instead.\n"
            f"{command}\n{result.combined()}"
        )
    raise RuntimeError(f"{message}: {command}\n{result.combined()}")


def issue_from_gh_payload(repo: str, payload: dict) -> AutoIssueFixIssue:
    labels = tuple(str(item.get("name", item)) for item in payload.get("labels", ()) if item)
    assignees = tuple(str(item.get("login", item)) for item in payload.get("assignees", ()) if item)
    return AutoIssueFixIssue(
        repo=normalize_repo(repo),
        number=int(payload.get("number") or 0),
        title=str(payload.get("title") or ""),
        body=str(payload.get("body") or ""),
        url=str(payload.get("url") or ""),
        labels=labels,
        state=str(payload.get("state") or "open"),
        assignees=assignees,
    )


def portable_path(path: str, placeholder: str, include_local_paths: bool = False) -> str:
    if include_local_paths:
        return redact_text(path)
    return placeholder


def default_run_id() -> str:
    return "auto_issue_fix_" + time.strftime("%Y%m%d_%H%M%S")


def default_evidence_dir(workspace_root: Path, run_id: str) -> Path:
    return workspace_root / ".repo-harness" / "auto-issue-fix" / run_id


def default_workdir(workspace_root: Path, run_id: str) -> Path:
    return workspace_root / ".repo-harness" / "auto-issue-fix-workspaces" / run_id


def _public_record(record: AutoIssueFixRunRecord, include_local_paths: bool) -> dict:
    data = asdict(record)
    data["workspace_path"] = portable_path(record.workspace_path, "<workspace>", include_local_paths)
    data["evidence_dir"] = portable_path(record.evidence_dir, "<evidence_dir>", include_local_paths)
    data["workdir"] = portable_path(record.workdir, "<workdir>", include_local_paths) if record.workdir else ""
    return json.loads(redact_text(json.dumps(data, ensure_ascii=False)))


def build_preview_review_gates(config: AutoIssueFixConfig, status: str) -> tuple[AutoIssueFixReviewGate, ...]:
    verdict = "pass" if status == "planned" else "block"
    action = (
        "dry-run preview recorded; live execution remains disabled in this version"
        if verdict == "pass"
        else "stop before live GitHub side effects and generate fallback evidence"
    )
    gates = []
    for stage, title, description in AUTO_REVIEW_STAGES:
        gates.append(
            AutoIssueFixReviewGate(
                stage=stage,
                title=title,
                verdict=verdict,
                summary=f"{description} Current mode is {config.mode}; automatic review is {config.auto_review}.",
                required_action=action,
            )
        )
    gates.append(
        AutoIssueFixReviewGate(
            stage="maintainer-trust",
            title="Maintainer trust review",
            verdict=verdict,
            summary="Check public PR-facing text for tool experiment notes before publication.",
            required_action=action,
        )
    )
    return tuple(gates)


def _review_gate_lines(review_gates: list[dict]) -> str:
    if not review_gates:
        return "- (none recorded)"
    return "\n".join(
        f"- `{item.get('stage', '-')}` {item.get('title', '')}: {item.get('verdict', '-')}"
        for item in review_gates
    )


def _changed_path_lines(paths) -> str:
    return "\n".join(f"- `{path}`" for path in paths) or "- (none recorded)"


def _validation_lines(tests) -> str:
    return "\n".join(
        f"- `{item.get('command', '-')}`: {item.get('status', '-')}" for item in tests
    ) or "- (not run)"


def review_gates_block_reason(review_gates: tuple[AutoIssueFixReviewGate, ...], max_review_repairs: int) -> str:
    for gate in review_gates:
        gate.validate()
        if gate.verdict == "block":
            return f"{gate.stage} review gate blocked the run"
        if gate.verdict == "needs_fix" and gate.repair_attempts >= max_review_repairs:
            return f"{gate.stage} review gate exceeded max review repairs"
    return ""


def render_evidence_templates(record: AutoIssueFixRunRecord, include_local_paths: bool = False) -> dict[str, str]:
    public_record = _public_record(record, include_local_paths)
    repo = public_record.get("repo") or "<repo>"
    issue = public_record.get("issue")
    issue_ref = f"#{issue}" if issue is not None else "(auto-discovered)"
    tests = public_record.get("tests") or []
    test_lines = _validation_lines(tests)
    fallback = public_record.get("fallback_reason") or ""
    fallback_block = f"\n\n## Fallback\n\nPR creation blocked: {fallback}\n" if fallback else ""
    status = public_record.get("status", "")
    pr_url = public_record.get("pr_url") or ""
    review_gates = public_record.get("review_gates") or []
    review_lines = _review_gate_lines(review_gates)

    run_record = f"""# Auto Issue Fix Run Record

## Summary

- Run ID: `{public_record['run_id']}`
- Mode: `{public_record['mode']}`
- Repository: `{repo}`
- Issue: `{issue_ref}`
- Status: `{status}`
- Workspace: `{public_record['workspace_path']}`
- Evidence directory: `{public_record['evidence_dir']}`
- PR URL: `{pr_url or '(none)'}`
- Automatic review: `{public_record.get('auto_review', 'required')}`
- Max review repairs: `{public_record.get('max_review_repairs', 2)}`
- Stage: `{public_record.get('stage') or '(none)'}`
- Branch: `{public_record.get('branch') or '(none)'}`
- Commit: `{public_record.get('commit') or '(none)'}`
- Baseline: `{public_record.get('baseline_status') or '(not recorded)'}`
- Workdir: `{portable_path(public_record.get('workdir') or '', '<workdir>', include_local_paths)}`

## Result

{public_record.get('summary') or '(none)'}

## Automatic Review Gates

{review_lines}

## Tests

{test_lines}
{fallback_block}
## Changed Paths

{_changed_path_lines(public_record.get('changed_paths', ()))}
"""

    if fallback:
        pr_body = f"""# PR-ready fallback

No pull request was created because the run was blocked before publication.

Repository: {repo}
Issue: {issue_ref}
Reason: {fallback}
"""
    else:
        pr_body = f"""## Summary

- Provides a focused candidate fix for the linked issue.
- Keeps the change scoped to the files listed below.

## Related Issue

Addresses {issue_ref}

## Validation

{test_lines}

## Scope

{_changed_path_lines(public_record.get('changed_paths', ()))}

## Notes for Maintainers

- This is a draft pull request for maintainer review.
- Please review the diff and validation results before considering merge.
"""

    formal_summary = f"""# RepoHarness Auto Issue Fix Formal Report Summary

This run is an Auto Issue Fix assisted workflow, not a claim that model output is trusted without governance. RepoHarness coordinates scoped file access, evidence generation, test gates, and PR preparation while preserving auditability.

- Repository: `{repo}`
- Issue: `{issue_ref}`
- Mode: `{public_record['mode']}`
- Status: `{status}`
- Evidence: `{public_record['evidence_dir']}`
- PR: `{pr_url or '(not created)'}`
- Automatic review: `{public_record.get('auto_review', 'required')}`
- Stage: `{public_record.get('stage') or '(none)'}`
- Branch: `{public_record.get('branch') or '(none)'}`

## Review Gates

{review_lines}
"""

    rendered = {
        "run-record.md": redact_text(run_record),
        "pr-body.md": redact_text(pr_body),
        "formal-report-summary.md": redact_text(formal_summary),
        "run-record.json": json.dumps(public_record, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
    }
    if fallback:
        rendered["pr-ready-fallback.md"] = redact_text(
            f"""# PR-ready fallback

Auto Issue Fix stopped before creating a pull request.

- Repository: `{repo}`
- Issue: `{issue_ref}`
- Reason: {fallback}
- Evidence: `{public_record['evidence_dir']}`
"""
        )
    return rendered


def write_evidence(record: AutoIssueFixRunRecord, include_local_paths: bool = False) -> dict[str, Path]:
    evidence_dir = Path(record.evidence_dir)
    evidence_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for name, content in render_evidence_templates(record, include_local_paths=include_local_paths).items():
        path = evidence_dir / name
        path.write_text(content, encoding="utf-8")
        written[name] = path
    public_record = _public_record(record, include_local_paths)
    reviews_dir = evidence_dir / "reviews"
    reviews_dir.mkdir(parents=True, exist_ok=True)
    decisions = []
    for gate in public_record.get("review_gates", ()):
        stage = str(gate.get("stage", "unknown"))
        json_path = reviews_dir / f"review-{stage}.json"
        md_path = reviews_dir / f"review-{stage}.md"
        json_path.write_text(json.dumps(gate, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
        md_path.write_text(
            redact_text(
                f"""# {gate.get('title', stage)}

- Stage: `{stage}`
- Verdict: `{gate.get('verdict', '-')}`
- Required action: {gate.get('required_action') or '(none)'}

{gate.get('summary') or ''}
"""
            ),
            encoding="utf-8",
        )
        written[str(json_path.relative_to(evidence_dir))] = json_path
        written[str(md_path.relative_to(evidence_dir))] = md_path
        decisions.append(
            {
                "run_id": public_record.get("run_id"),
                "stage": stage,
                "verdict": gate.get("verdict"),
                "required_action": gate.get("required_action", ""),
            }
        )
    decision_log_path = evidence_dir / "decision-log.jsonl"
    decision_log_path.write_text(
        "".join(json.dumps(item, ensure_ascii=False, sort_keys=True) + "\n" for item in decisions),
        encoding="utf-8",
    )
    written["decision-log.jsonl"] = decision_log_path
    checkpoint_path = evidence_dir / "checkpoint.json"
    checkpoint = {
        "run_id": public_record.get("run_id"),
        "mode": public_record.get("mode"),
        "status": public_record.get("status"),
        "stage": public_record.get("stage") or "",
        "branch": public_record.get("branch") or "",
        "commit": public_record.get("commit") or "",
        "pr_url": public_record.get("pr_url") or "",
        "resume_from": public_record.get("resume_from") or "",
        "next_action": _checkpoint_next_action(public_record),
    }
    checkpoint_path.write_text(json.dumps(checkpoint, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
    written["checkpoint.json"] = checkpoint_path
    return written


def _checkpoint_next_action(public_record: dict) -> str:
    status = public_record.get("status")
    if status == "completed":
        return "draft PR created; review upstream PR and evidence"
    if status == "paused":
        return "resume after review-gated confirmation"
    if status in {"blocked", "failed"}:
        return "inspect fallback evidence before rerunning"
    if status == "planned":
        return "dry-run preview recorded; rerun without --dry-run for live execution"
    return "inspect evidence and checkpoint before continuing"


def write_evidence_file(evidence_dir: Path, name: str, content: str, include_local_paths: bool = False) -> Path:
    path = evidence_dir / name
    path.parent.mkdir(parents=True, exist_ok=True)
    text = redact_text(str(content))
    if not include_local_paths:
        text = text.replace(str(evidence_dir), "<evidence_dir>")
    path.write_text(text, encoding="utf-8")
    return path


def write_json_evidence(evidence_dir: Path, name: str, payload: dict, include_local_paths: bool = False) -> Path:
    return write_evidence_file(
        evidence_dir,
        name,
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        include_local_paths=include_local_paths,
    )


def infer_test_commands(repo_root: Path) -> tuple[str, ...]:
    if (repo_root / "pyproject.toml").exists() or (repo_root / "pytest.ini").exists():
        if (repo_root / "tests").exists():
            return ("python -m pytest -q",)
    if (repo_root / "package.json").exists():
        return ("npm test",)
    if (repo_root / "go.mod").exists():
        return ("go test ./...",)
    if (repo_root / "Cargo.toml").exists():
        return ("cargo test",)
    return ()


def run_shell_command(command: str, cwd: Path, timeout: int = 600) -> CommandResult:
    completed = subprocess.run(
        command,
        cwd=str(cwd),
        text=True,
        capture_output=True,
        shell=True,
        timeout=timeout,
        check=False,
    )
    return CommandResult(
        args=(command,),
        cwd=str(cwd.resolve()),
        returncode=int(completed.returncode),
        stdout=completed.stdout or "",
        stderr=completed.stderr or "",
    )


def run_test_commands(commands: tuple[str, ...], cwd: Path, log_path: Path) -> list[dict]:
    results = []
    blocks = []
    for command in commands:
        result = run_shell_command(command, cwd=cwd)
        status = "passed" if result.ok else "failed"
        results.append({"command": command, "status": status, "returncode": result.returncode})
        blocks.append(
            f"$ {command}\nreturncode: {result.returncode}\n\nSTDOUT\n{result.stdout}\n\nSTDERR\n{result.stderr}\n"
        )
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_path.write_text("\n\n".join(blocks) if blocks else "(no test command inferred or provided)\n", encoding="utf-8")
    return results


def changed_paths(cwd: Path) -> tuple[str, ...]:
    result = run_command(["git", "diff", "--name-only"], cwd=cwd)
    require_ok(result, "git diff --name-only failed")
    return tuple(line.strip() for line in result.stdout.splitlines() if line.strip())


def git_diff(cwd: Path) -> str:
    result = run_command(["git", "diff", "--binary"], cwd=cwd)
    require_ok(result, "git diff failed")
    return result.stdout


def scan_diff_gate(cwd: Path, paths: tuple[str, ...], diff_text: str) -> str:
    if not paths:
        return "no changed files"
    blocked_prefixes = (".git/", ".repo-harness/", ".venv/", "venv/", "node_modules/")
    for path in paths:
        normalized = path.replace("\\", "/")
        if normalized.startswith(blocked_prefixes):
            return f"diff gate blocked generated or internal path: {path}"
    diff_check = run_command(["git", "diff", "--check"], cwd=cwd)
    if not diff_check.ok:
        return "git diff --check failed"
    if redact_text(diff_text) != diff_text:
        return "secret-shaped content detected in diff"
    return ""


def build_rule_review_gates(
    config: AutoIssueFixConfig,
    *,
    issue: AutoIssueFixIssue | None,
    diff_block: str,
    maintainer_trust_block: str = "",
    tests: list[dict],
    changed: tuple[str, ...],
) -> tuple[AutoIssueFixReviewGate, ...]:
    gates = []
    has_failed_tests = any(item.get("status") == "failed" for item in tests)
    for stage, title, description in AUTO_REVIEW_STAGES:
        verdict = "pass"
        action = "continue"
        summary = description
        if stage == "task" and issue is None:
            verdict = "block"
            action = "select an issue before running Auto Issue Fix"
        elif stage == "diff" and diff_block:
            verdict = "block"
            action = diff_block
            summary = f"{description} {diff_block}"
        elif stage == "tests" and not tests:
            verdict = "block"
            action = "provide --test-command or add a detectable project test command before PR creation"
            summary = f"{description} No validation command was provided or inferred."
        elif stage == "tests" and has_failed_tests:
            verdict = "block"
            action = "fix failing validation commands before PR creation"
            summary = f"{description} One or more validation commands failed."
        elif stage == "pr-readiness" and not changed:
            verdict = "block"
            action = "produce a non-empty diff before PR creation"
            summary = f"{description} No changed files were found."
        gates.append(
            AutoIssueFixReviewGate(
                stage=stage,
                title=title,
                verdict=verdict,
                summary=summary,
                required_action=action,
            )
        )
    gates.append(
        AutoIssueFixReviewGate(
            stage="maintainer-trust",
            title="Maintainer trust review",
            verdict="block" if maintainer_trust_block else "pass",
            summary=maintainer_trust_block
            or "Public PR title, body, commit message, and branch are maintainer-facing.",
            required_action=maintainer_trust_block or "continue",
        )
    )
    return tuple(gates)


def score_issue(issue: AutoIssueFixIssue) -> int:
    text = f"{issue.title}\n{issue.body}".lower()
    labels = {label.lower() for label in issue.labels}
    score = 0
    if labels & {"bug", "type: bug", "test", "tests", "good first issue"}:
        score += 3
    if any(word in text for word in ("reproduce", "repro", "steps", "expected", "actual")):
        score += 3
    if any(word in text for word in ("pytest", "npm test", "go test", "cargo test", "test")):
        score += 2
    if not issue.assignees:
        score += 1
    if any(word in text for word in ("aws", "gcp", "azure", "api key", "credential", "database")):
        score -= 5
    if any(word in text for word in ("refactor", "rewrite", "architecture", "design proposal")):
        score -= 4
    return score


def discover_issue(config: AutoIssueFixConfig, backend: GhCliBackend, evidence_dir: Path) -> AutoIssueFixIssue:
    repos = [normalize_repo(config.repo)] if config.repo else []
    if not repos:
        repos = backend.search_repos(limit=10)
    candidates = []
    for repo in repos[:10]:
        for issue in backend.issue_list(repo, limit=20):
            candidates.append((score_issue(issue), issue))
    candidates.sort(key=lambda item: item[0], reverse=True)
    payload = [{"score": score, **issue.to_dict()} for score, issue in candidates]
    write_json_evidence(evidence_dir, "issue-selection.json", {"candidates": payload})
    lines = ["# Issue Selection", ""]
    for score, issue in candidates[:10]:
        lines.append(f"- score={score} `{issue.repo}#{issue.number}` {issue.title}")
    write_evidence_file(evidence_dir, "issue-selection.md", "\n".join(lines) + "\n")
    if not candidates or candidates[0][0] < 1:
        raise RuntimeError("no suitable issue found during discovery")
    return candidates[0][1]


def _build_auto_issue_fix_model_client(config: AutoIssueFixConfig):
    from argparse import Namespace

    from repo_harness.cli import _build_model_client

    args = Namespace(
        provider=config.provider,
        model=config.model,
        base_url=config.base_url,
        host=config.host,
        temperature=config.temperature,
        top_p=config.top_p,
        ollama_timeout=config.ollama_timeout,
        openai_timeout=config.openai_timeout,
    )
    return _build_model_client(args)


def run_repoharness_fix_turn(config: AutoIssueFixConfig, issue: AutoIssueFixIssue, clone_dir: Path, model_client=None) -> str:
    from repo_harness.runtime import RepoHarness, SessionStore
    from repo_harness.workspace import WorkspaceContext

    model = model_client or _build_auto_issue_fix_model_client(config)
    session_store = SessionStore(str(clone_dir / ".repo-harness" / "sessions"))
    agent = RepoHarness(
        model_client=model,
        workspace=WorkspaceContext.build(clone_dir),
        session_store=session_store,
        approval_policy="auto",
        max_steps=config.max_steps,
        max_new_tokens=config.max_new_tokens,
        read_only=False,
    )
    prompt = f"""You are running inside RepoHarness Auto Issue Fix.

Repository: {issue.repo}
Issue: #{issue.number} {issue.title}
Issue URL: {issue.url}

Issue body:
{issue.body}

Task:
1. Read README, contribution/test configuration, and the relevant source files.
2. Make the smallest useful fix for this issue.
3. Keep changes scoped and avoid unrelated formatting.
4. Run or explain the relevant validation command if available.
5. Finish with a concise summary.
"""
    return agent.ask(prompt)


def maybe_confirm_review_gate(config: AutoIssueFixConfig, stage: str, evidence_dir: Path) -> bool:
    if config.mode != "review-gated":
        return True
    checkpoint = {
        "stage": f"awaiting_human_confirmation:{stage}",
        "mode": config.mode,
        "next_action": f"confirm before {stage}",
    }
    write_json_evidence(evidence_dir, "checkpoint.json", checkpoint, include_local_paths=config.include_local_paths)
    if not sys.stdin.isatty():
        return False
    answer = input(f"Auto Issue Fix review-gated checkpoint before {stage}. Continue? [y/N] ").strip().lower()
    return answer in {"y", "yes"}


def run_live_auto_issue_fix(config: AutoIssueFixConfig, model_client=None, gh_backend=None) -> AutoIssueFixRunRecord:
    config.validate()
    workspace_root = Path(config.workspace_root or ".").resolve()
    run_id = default_run_id()
    evidence_dir = Path(config.evidence_dir).resolve() if config.evidence_dir else default_evidence_dir(workspace_root, run_id)
    workdir = Path(config.workdir).resolve() if config.workdir else default_workdir(workspace_root, run_id)
    evidence_dir.mkdir(parents=True, exist_ok=True)
    backend = gh_backend or GhCliBackend()
    context = LiveRunContext(config, run_id, workspace_root, evidence_dir, workdir)

    try:
        context.stage = "issue"
        issue = discover_issue(config, backend, evidence_dir) if config.discover else backend.issue_view(config.repo, int(config.issue or 0))
        context.issue = issue
        write_json_evidence(evidence_dir, "issue.json", issue.to_dict(), include_local_paths=config.include_local_paths)

        context.stage = "clone"
        if workdir.exists():
            raise RuntimeError(f"workdir already exists: {workdir}")
        workdir.parent.mkdir(parents=True, exist_ok=True)
        backend.clone(issue.repo, workdir)
        context.branch = f"repo-harness-auto-issue-fix-{issue.number}"
        require_ok(run_command(["git", "checkout", "-b", context.branch], cwd=workdir), "git checkout branch failed")

        test_commands = config.test_commands or infer_test_commands(workdir)
        context.stage = "baseline"
        baseline_tests = run_test_commands(test_commands, workdir, evidence_dir / "baseline-repro.log")
        context.baseline_status = "failed" if any(item["status"] == "failed" for item in baseline_tests) else ("passed" if baseline_tests else "not_run")

        context.stage = "fix"
        fix_output = run_repoharness_fix_turn(config, issue, workdir, model_client=model_client)
        write_evidence_file(evidence_dir, "fix-run.log", fix_output, include_local_paths=config.include_local_paths)

        context.stage = "test"
        context.tests = run_test_commands(test_commands, workdir, evidence_dir / "test-after-fix.log")
        diff_text = git_diff(workdir)
        write_evidence_file(evidence_dir, "git-diff.patch", diff_text, include_local_paths=config.include_local_paths)
        context.changed_paths = list(changed_paths(workdir))
        diff_block = scan_diff_gate(workdir, tuple(context.changed_paths), diff_text)
        message = config.commit_message or f"fix: address issue {issue.number}"
        pr_title = f"Fix #{issue.number}: {issue.title}"
        trust_record = _record_from_live_context(
            context,
            status="pr_ready",
            summary="Prepared a maintainer-facing draft PR body.",
        )
        public_pr_body = render_evidence_templates(trust_record, include_local_paths=config.include_local_paths)["pr-body.md"]
        trust_block = maintainer_trust_block_reason(
            title=pr_title,
            body=public_pr_body,
            commit_message=message,
            branch=context.branch,
        )
        context.review_gates = list(
            build_rule_review_gates(
                config,
                issue=issue,
                diff_block=diff_block,
                maintainer_trust_block=trust_block,
                tests=context.tests,
                changed=tuple(context.changed_paths),
            )
        )
        block_reason = review_gates_block_reason(tuple(context.review_gates), config.max_review_repairs)
        if block_reason:
            context.fallback_reason = block_reason
            context.stage = "blocked"
            return _record_from_live_context(context, status="blocked", summary="Auto Issue Fix stopped before PR creation.")

        if not maybe_confirm_review_gate(config, "commit", evidence_dir):
            context.stage = "paused"
            return _record_from_live_context(context, status="paused", summary="Auto Issue Fix paused before commit for review-gated confirmation.")

        context.stage = "commit"
        require_ok(run_command(["git", "add", "--", *context.changed_paths], cwd=workdir), "git add failed")
        require_ok(run_command(["git", "commit", "-m", message], cwd=workdir), "git commit failed")
        commit_result = run_command(["git", "rev-parse", "HEAD"], cwd=workdir)
        require_ok(commit_result, "git rev-parse failed")
        context.commit = commit_result.stdout.strip()

        if not maybe_confirm_review_gate(config, "push", evidence_dir):
            context.stage = "paused"
            return _record_from_live_context(context, status="paused", summary="Auto Issue Fix paused before push for review-gated confirmation.")

        context.stage = "push"
        backend.ensure_fork_remote(workdir)
        require_ok(run_command(["git", "push", "-u", "fork", context.branch], cwd=workdir), "git push fork failed")

        if not maybe_confirm_review_gate(config, "pr", evidence_dir):
            context.stage = "paused"
            return _record_from_live_context(context, status="paused", summary="Auto Issue Fix paused before draft PR creation.")

        context.stage = "pr"
        pre_pr_record = _record_from_live_context(context, status="pr_ready", summary="Auto Issue Fix prepared a draft PR body.")
        write_evidence(pre_pr_record, include_local_paths=config.include_local_paths)
        base = backend.default_branch(issue.repo)
        context.pr_url = backend.create_pr(
            issue.repo,
            context.branch,
            pr_title,
            evidence_dir / "pr-body.md",
            base,
        )
        write_evidence_file(evidence_dir, "pr-url.txt", context.pr_url + "\n", include_local_paths=config.include_local_paths)
        context.stage = "completed"
        return _record_from_live_context(context, status="completed", summary="Auto Issue Fix created a draft pull request.")
    except Exception as exc:
        context.fallback_reason = str(exc)
        context.review_gates = list(
            context.review_gates
            or (
                AutoIssueFixReviewGate(
                    stage="task",
                    title="任务审查",
                    verdict="block",
                    summary=str(exc),
                    required_action="inspect fallback evidence and rerun after fixing the failure",
                ),
            )
        )
        return _record_from_live_context(context, status="failed", summary="Auto Issue Fix failed and wrote fallback evidence.")


def _record_from_live_context(context: LiveRunContext, status: str, summary: str) -> AutoIssueFixRunRecord:
    issue = context.issue
    return AutoIssueFixRunRecord(
        run_id=context.run_id,
        mode=context.config.mode,
        repo=issue.repo if issue else (context.config.repo or f"auto-discover:{context.config.source}"),
        issue=issue.number if issue else context.config.issue,
        workspace_path=str(context.workspace_root),
        evidence_dir=str(context.evidence_dir),
        status=status,
        summary=summary,
        tests=context.tests,
        pr_url=context.pr_url,
        fallback_reason=context.fallback_reason,
        selected_issue_url=issue.url if issue else "",
        changed_paths=tuple(context.changed_paths),
        auto_review=context.config.auto_review,
        max_review_repairs=context.config.max_review_repairs,
        review_gates=tuple(context.review_gates),
        resume_from=context.config.resume,
        stage=context.stage,
        branch=context.branch,
        commit=context.commit,
        baseline_status=context.baseline_status,
        workdir=str(context.workdir),
    )


def _split_csv(values: list[str] | None, default: tuple[str, ...]) -> tuple[str, ...]:
    items: list[str] = []
    for value in values or ():
        items.extend(part.strip() for part in str(value).split(",") if part.strip())
    return tuple(items) or default


def build_auto_issue_fix_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="repo-harness auto-issue-fix",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Prepare a governed Auto Issue Fix run with RepoHarness evidence artifacts.",
    )
    parser.add_argument("--repo", default="", help="GitHub repository URL or owner/name.")
    parser.add_argument("--issue", type=int, default=None, help="Issue number to fix.")
    parser.add_argument("--discover", action="store_true", help="Discover a candidate issue instead of using --issue.")
    parser.add_argument("--source", choices=("trending", "repo"), default="trending", help="Discovery source.")
    parser.add_argument("--criteria", action="append", default=[], help="Comma-separated discovery criteria.")
    parser.add_argument("--mode", choices=AUTO_ISSUE_FIX_MODES, default="review-gated", help="Automation mode.")
    parser.add_argument("--evidence-dir", default=None, help="Evidence output directory.")
    parser.add_argument("--workspace-root", default=".", help="Workspace root for the Auto Issue Fix run.")
    parser.add_argument("--workdir", default=None, help="Isolated clone directory for live Auto Issue Fix execution.")
    parser.add_argument("--test-command", action="append", default=[], help="Validation command to record or run.")
    parser.add_argument("--dry-run", action="store_true", help="Generate the evidence plan without clone, push, or PR side effects.")
    parser.add_argument("--include-local-paths", action="store_true", help="Include local absolute paths in evidence artifacts.")
    parser.add_argument("--auto-review", choices=AUTO_REVIEW_MODES, default="required", help="Automatic review gate policy.")
    parser.add_argument("--max-review-repairs", type=int, default=2, help="Maximum bounded repair loops after a needs_fix verdict.")
    parser.add_argument("--resume", default="", help="Resume from a previous Auto Issue Fix run id when live runner support is enabled.")
    parser.add_argument("--provider", choices=("ollama", "openai", "chat-completions", "anthropic", "deepseek"), default="openai", help="Model backend for live fix turns.")
    parser.add_argument("--model", default=None, help="Model name override for live fix turns.")
    parser.add_argument("--base-url", default=None, help="OpenAI/Anthropic-compatible base URL override.")
    parser.add_argument("--host", default=None, help="Ollama host override.")
    parser.add_argument("--temperature", type=float, default=0.2, help="Model temperature for live fix turns.")
    parser.add_argument("--top-p", type=float, default=0.9, help="Ollama top_p for live fix turns.")
    parser.add_argument("--ollama-timeout", type=int, default=300, help="Ollama request timeout.")
    parser.add_argument("--openai-timeout", type=int, default=300, help="OpenAI/Anthropic-compatible request timeout.")
    parser.add_argument("--max-steps", type=int, default=50, help="RepoHarness max tool loop steps for live fix turns.")
    parser.add_argument("--max-new-tokens", type=int, default=8192, help="RepoHarness max new tokens for live fix turns.")
    parser.add_argument("--commit-message", default="", help="Commit message override for live Auto Issue Fix execution.")
    return parser


def config_from_args(args) -> AutoIssueFixConfig:
    return AutoIssueFixConfig(
        repo=str(args.repo or ""),
        issue=args.issue,
        discover=bool(args.discover),
        source=str(args.source or "trending"),
        criteria=_split_csv(args.criteria, ("bug", "test")),
        mode=str(args.mode or "review-gated"),
        evidence_dir=Path(args.evidence_dir) if args.evidence_dir else None,
        workspace_root=Path(args.workspace_root or "."),
        workdir=Path(args.workdir) if args.workdir else None,
        dry_run=bool(args.dry_run),
        include_local_paths=bool(args.include_local_paths),
        test_commands=tuple(str(item) for item in args.test_command or ()),
        auto_review=str(args.auto_review or "required"),
        max_review_repairs=int(args.max_review_repairs),
        resume=str(args.resume or ""),
        provider=str(args.provider or "openai"),
        model=args.model,
        base_url=args.base_url,
        host=args.host,
        temperature=float(args.temperature),
        top_p=float(args.top_p),
        ollama_timeout=int(args.ollama_timeout),
        openai_timeout=int(args.openai_timeout),
        max_steps=int(args.max_steps),
        max_new_tokens=int(args.max_new_tokens),
        commit_message=str(args.commit_message or ""),
    )


def run_auto_issue_fix(config: AutoIssueFixConfig, model_client=None, gh_backend=None) -> AutoIssueFixRunRecord:
    config.validate()
    if not config.dry_run:
        return run_live_auto_issue_fix(config, model_client=model_client, gh_backend=gh_backend)
    workspace_root = Path(config.workspace_root or ".").resolve()
    run_id = default_run_id()
    evidence_dir = Path(config.evidence_dir).resolve() if config.evidence_dir else default_evidence_dir(workspace_root, run_id)
    status = "planned" if config.dry_run else "blocked"
    fallback_reason = "" if config.dry_run else "live clone/fix/test/push/PR runner is not enabled in this version"
    issue_url = ""
    if config.repo and config.issue is not None:
        repo_ref = config.repo.rstrip("/")
        issue_url = f"{repo_ref}/issues/{config.issue}" if repo_ref.startswith("http") else f"https://github.com/{repo_ref}/issues/{config.issue}"
    tests = [
        {"command": command, "status": "not_run" if config.dry_run else "blocked"}
        for command in config.test_commands
    ]
    summary = (
        "Auto Issue Fix safe preview created a portable evidence scaffold with automatic review gates."
        if config.dry_run
        else "Auto Issue Fix live execution is blocked until the real execution runner is enabled."
    )
    review_gates = build_preview_review_gates(config, status)
    return AutoIssueFixRunRecord(
        run_id=run_id,
        mode=config.mode,
        repo=config.repo or f"auto-discover:{config.source}",
        issue=config.issue,
        workspace_path=str(workspace_root),
        evidence_dir=str(evidence_dir),
        status=status,
        summary=summary,
        tests=tests,
        fallback_reason=fallback_reason,
        selected_issue_url=issue_url,
        auto_review=config.auto_review,
        max_review_repairs=config.max_review_repairs,
        review_gates=review_gates,
        resume_from=config.resume,
    )


def run_auto_issue_fix_argv(argv: list[str] | None = None) -> tuple[int, str, AutoIssueFixRunRecord | None]:
    parser = build_auto_issue_fix_arg_parser()
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:
        return int(exc.code or 0), "", None
    config = config_from_args(args)
    try:
        record = run_auto_issue_fix(config)
    except ValueError as exc:
        return 2, f"auto-issue-fix: {exc}", None
    write_evidence(record, include_local_paths=config.include_local_paths)
    lines = []
    lines.append("Risk notice: " + config.risk_notice())
    if config.dry_run:
        lines.append("Auto Issue Fix safe preview complete")
    elif record.status == "completed":
        lines.append("Auto Issue Fix draft PR created")
    elif record.status == "paused":
        lines.append("Auto Issue Fix paused for review-gated confirmation")
    else:
        lines.append("Auto Issue Fix evidence generated; live execution did not create a PR")
    lines.append(f"Evidence: {record.evidence_dir}")
    return (0 if config.dry_run or record.status == "completed" else 1), "\n".join(lines), record


def _guided_auto_issue_fix_argv(workspace_root: Path | str, input_func=input) -> tuple[list[str], str] | tuple[None, str]:
    print("Auto Issue Fix guided mode")
    print("Mode: press Enter for the recommended review-gated live execution, type dry-run for safe preview, or draft-auto for draft PR automation.")
    mode_value = input_func("Mode [review-gated/draft-auto/dry-run]: ").strip().lower()
    dry_run = mode_value == "dry-run"
    mode = "draft-auto" if mode_value == "draft-auto" else "review-gated"
    repo = input_func("Repository (owner/name or GitHub URL; blank to discover from trending): ").strip()
    if repo:
        issue_text = input_func("Issue number (blank to discover within this repository): ").strip()
    else:
        issue_text = ""
    test_command = input_func("Test command (optional; blank to infer): ").strip()
    if repo and issue_text:
        if not issue_text.isdigit():
            return None, "auto-issue-fix: issue number must be a positive integer"
        argv = ["--repo", repo, "--issue", issue_text, "--mode", mode, "--workspace-root", str(workspace_root)]
    elif repo:
        argv = [
            "--discover",
            "--source",
            "repo",
            "--repo",
            repo,
            "--criteria",
            "bug,test",
            "--mode",
            mode,
            "--workspace-root",
            str(workspace_root),
        ]
    else:
        argv = [
            "--discover",
            "--source",
            "trending",
            "--criteria",
            "bug,test",
            "--mode",
            mode,
            "--workspace-root",
            str(workspace_root),
        ]
    if dry_run:
        argv.append("--dry-run")
    if test_command:
        argv.extend(["--test-command", test_command])
    summary = " ".join(shlex.quote(item) for item in ["repo-harness", "auto-issue-fix", *argv])
    return argv, (
        "Auto Issue Fix guided command prepared:\n"
        f"{summary}\n"
        "Reminder: review-gated pauses before commit, push, and draft PR creation."
    )


def handle_auto_issue_fix_repl_command(
    body: str,
    workspace_root: Path | str = ".",
    *,
    interactive: bool = False,
    input_func=input,
) -> tuple[int, str]:
    body = str(body or "").strip()
    if not body:
        if not interactive:
            return (
                2,
                "usage: /auto-issue-fix --repo owner/name --issue 123 [--dry-run]\n"
                "Run `/auto-issue-fix` in the interactive REPL to use guided mode.",
            )
        guided_argv, prefix = _guided_auto_issue_fix_argv(workspace_root, input_func=input_func)
        if guided_argv is None:
            return 2, prefix
        argv = guided_argv
        prefix += "\n"
    else:
        try:
            argv = shlex.split(body)
        except ValueError as exc:
            return 2, f"auto-issue-fix: could not parse arguments: {exc}"
        if "--workspace-root" not in argv:
            argv.extend(["--workspace-root", str(workspace_root)])
        prefix = ""
    code, output, _record = run_auto_issue_fix_argv(argv)
    return code, prefix + output


def handle_auto_issue_fix_command(argv: list[str] | None = None) -> int:
    code, output, _record = run_auto_issue_fix_argv(argv)
    if output:
        stream = os.sys.stderr if code == 2 else os.sys.stdout
        print(output, file=stream)
    return code
