"""Auto Issue Fix configuration and record types."""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass, field
from pathlib import Path

# Verification contract shared with repo_harness/task_state.py. Kept local to
# avoid an import cycle (auto_issue_fix config is imported by the runtime's
# fix-turn path in some flows). Values must match task_state's constants.
VERIFICATION_NOT_RUN = "not_run"
VERIFICATION_PASSED = "passed"
VERIFICATION_FAILED = "failed"

AUTO_ISSUE_FIX_MODES = ("review-gated", "draft-auto")
AUTO_REVIEW_MODES = ("required",)
AUTO_REVIEW_VERDICTS = ("pass", "needs_fix", "block")
AUTO_REVIEW_STAGES = (
    ("task", "Task Review", "Confirm repository, issue, goal, boundaries, and risk."),
    ("plan", "Plan Review", "Check the execution plan, write scope, test strategy, and fallback path."),
    ("context", "Context Review", "Confirm required files and issue background are available for execution."),
    ("diff", "Diff Review", "Check for unrelated edits, generated artifacts, or broad rewrites."),
    ("tests", "Test Review", "Check baseline, post-fix validation, and failure logs against the issue."),
    ("security", "Security Review", "Check secrets, path leaks, risky commands, write scope, and supply-chain risk."),
    ("pr-readiness", "PR Readiness Review", "Check PR body, evidence, change summary, validation, and risk notes."),
)
PUBLIC_PR_BODY_FORBIDDEN_TERMS = (
    "AI",
    "RepoHarness",
    "repo-harness",
    "MiMo",
    "experiment",
    "model",
    "trace",
    "benchmark",
    "dogfood",
    "generated by",
)
GITHUB_BLOCKED_ERROR_PATTERNS = (
    "blocked from",
    "you have been blocked",
    "cannot perform this action",
    "permission denied",
    "forbidden",
    "resource not accessible",
)
SECRET_PATTERNS = (
    re.compile(r"\b(?:sk|gho|ghp|github_pat)[_-][A-Za-z0-9_=-]{6,}"),
    re.compile(r"\b(?:[A-Z][A-Z0-9_]*_API_KEY|GITHUB_TOKEN|GH_TOKEN|COOKIE|cookie)\s*=\s*[^\s]+", re.I),
    re.compile(r"\b(?:token|api[_-]?key|cookie)\s*[:=]\s*[^\s]+", re.I),
)


@dataclass(frozen=True)
class AutoIssueFixConfig:
    repo: str = ""
    issue: int | None = None
    discover: bool = False
    source: str = "trending"
    criteria: tuple[str, ...] = ("bug", "test")
    mode: str = "review-gated"
    evidence_dir: Path | None = None
    workspace_root: Path | None = None
    dry_run: bool = False
    include_local_paths: bool = False
    test_commands: tuple[str, ...] = ()
    auto_review: str = "required"
    max_review_repairs: int = 2
    resume: str = ""
    workdir: Path | None = None
    provider: str = ""
    model: str | None = None
    base_url: str | None = None
    host: str | None = None
    temperature: float = 0.2
    top_p: float = 0.9
    ollama_timeout: int = 300
    openai_timeout: int = 300
    max_steps: int = 50
    max_new_tokens: int = 8192
    commit_message: str = ""
    maintainer_access_confirmed: bool = False

    def validate(self) -> None:
        if self.mode not in AUTO_ISSUE_FIX_MODES:
            raise ValueError(f"mode must be one of: {', '.join(AUTO_ISSUE_FIX_MODES)}")
        if self.auto_review not in AUTO_REVIEW_MODES:
            raise ValueError("auto-review must be required")
        if self.mode == "draft-auto" and self.auto_review != "required":
            raise ValueError("draft-auto cannot disable automatic review gates")
        if self.max_review_repairs < 0:
            raise ValueError("--max-review-repairs must be zero or greater")
        if self.max_steps <= 0:
            raise ValueError("--max-steps must be greater than zero")
        if self.max_new_tokens <= 0:
            raise ValueError("--max-new-tokens must be greater than zero")
        if not self.discover and (not self.repo or self.issue is None):
            raise ValueError("auto-issue-fix requires --repo and --issue unless --discover is set")
        if self.discover and self.repo and self.issue is not None:
            raise ValueError("--discover cannot be combined with both --repo and --issue")

    def risk_notice(self) -> str:
        if self.mode == "draft-auto":
            return (
                "draft-auto skips human pauses only after automatic review gates pass. "
                "A block verdict stops the run and writes fallback evidence instead of creating a draft PR."
            )
        return (
            "review-gated uses the same automatic review gates, then pauses for human confirmation "
            "at high-risk checkpoints."
        )


@dataclass(frozen=True)
class AutoIssueFixReviewGate:
    stage: str
    title: str
    verdict: str
    summary: str
    required_action: str = ""
    repair_attempts: int = 0

    def validate(self) -> None:
        if self.verdict not in AUTO_REVIEW_VERDICTS:
            raise ValueError(f"review verdict must be one of: {', '.join(AUTO_REVIEW_VERDICTS)}")


@dataclass(frozen=True)
class AutoIssueFixRunRecord:
    run_id: str
    mode: str
    repo: str
    issue: int | None
    workspace_path: str
    evidence_dir: str
    status: str
    summary: str
    tests: list[dict]
    pr_url: str = ""
    fallback_reason: str = ""
    selected_issue_url: str = ""
    changed_paths: tuple[str, ...] = ()
    auto_review: str = "required"
    max_review_repairs: int = 2
    review_gates: tuple[AutoIssueFixReviewGate, ...] = ()
    resume_from: str = ""
    stage: str = ""
    branch: str = ""
    commit: str = ""
    baseline_status: str = ""
    workdir: str = ""
    metrics: dict = field(default_factory=dict)

    @property
    def verification_status(self) -> str:
        """Derived from the tests that actually ran (G1 contract).

        All passed -> passed; any failed -> failed; anything not_run (including
        a dry-run stub or a skipped command) -> not_run. A command that never
        ran must never count as verification passed.
        """
        if not self.tests:
            return VERIFICATION_NOT_RUN
        statuses = {str(item.get("status", "")) for item in self.tests}
        if "failed" in statuses:
            return VERIFICATION_FAILED
        if statuses == {"passed"}:
            return VERIFICATION_PASSED
        return VERIFICATION_NOT_RUN

    @property
    def verification_evidence(self) -> list[dict]:
        """The executed test results, as structured verification evidence."""
        return [
            {
                "command": item.get("command", ""),
                "returncode": item.get("returncode"),
                "status": item.get("status", ""),
                "output_summary": str(item.get("output_summary", "")),
            }
            for item in self.tests
        ]


@dataclass(frozen=True)
class CommandResult:
    args: tuple[str, ...]
    cwd: str
    returncode: int
    stdout: str
    stderr: str

    @property
    def ok(self) -> bool:
        return self.returncode == 0

    def combined(self) -> str:
        return (self.stdout + "\n" + self.stderr).strip()


@dataclass(frozen=True)
class AutoIssueFixIssue:
    repo: str
    number: int
    title: str
    body: str = ""
    url: str = ""
    labels: tuple[str, ...] = ()
    state: str = "open"
    assignees: tuple[str, ...] = ()

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class LiveRunContext:
    config: AutoIssueFixConfig
    run_id: str
    workspace_root: Path
    evidence_dir: Path
    workdir: Path
    issue: AutoIssueFixIssue | None = None
    branch: str = ""
    pr_url: str = ""
    commit: str = ""
    changed_paths: list[str] = field(default_factory=list)
    tests: list[dict] = field(default_factory=list)
    review_gates: list[AutoIssueFixReviewGate] = field(default_factory=list)
    fallback_reason: str = ""
    stage: str = "initialized"
    baseline_status: str = ""
