"""Evidence rendering and portable report helpers for Auto Issue Fix."""

from __future__ import annotations

import json
import re
from dataclasses import asdict
from pathlib import Path
from uuid import uuid4

from ..workspace import id_timestamp
from .config import (
    AUTO_REVIEW_STAGES,
    AUTO_REVIEW_VERDICTS,
    AutoIssueFixConfig,
    AutoIssueFixReviewGate,
    AutoIssueFixRunRecord,
)
from .security import redact_text

WINDOWS_ABSOLUTE_PATH_RE = re.compile(r"\b[A-Za-z]:\\[^\s`'\"<>]+")
POSIX_ABSOLUTE_PATH_RE = re.compile(r"(?<![:\w])/(?:Users|home|tmp|var|private|mnt|workspace|repo|opt)[^\s`'\"<>]*")
PUBLIC_PR_FORBIDDEN_PATTERNS = (
    re.compile(r"\bAI\b", re.I),
    re.compile(r"\bRepoHarness\b", re.I),
    re.compile(r"\brepo-harness\b", re.I),
    re.compile(r"\bMiMo\b", re.I),
    re.compile(r"\bexperiment\b", re.I),
    re.compile(r"\bmodel\b", re.I),
    re.compile(r"\btrace\b", re.I),
    re.compile(r"\bbenchmark\b", re.I),
    re.compile(r"\bdogfood\b", re.I),
    re.compile(r"generated by", re.I),
)


def _portable_text(text: str, include_local_paths: bool = False) -> str:
    value = redact_text(str(text or ""))
    if include_local_paths:
        return value
    value = WINDOWS_ABSOLUTE_PATH_RE.sub("<path>", value)
    value = POSIX_ABSOLUTE_PATH_RE.sub("<path>", value)
    return value


def _public_pr_text(text: str) -> str:
    value = _portable_text(text, include_local_paths=False)
    for pattern in PUBLIC_PR_FORBIDDEN_PATTERNS:
        value = pattern.sub("<redacted>", value)
    return value


def portable_path(path: str, placeholder: str, include_local_paths: bool = False) -> str:
    if include_local_paths:
        return redact_text(path)
    return placeholder


def default_run_id() -> str:
    # Same contract as the session, task and run ids in runtime.py: a UTC stamp
    # so ordering survives a DST fall-back, and a random suffix so two runs
    # started in the same second do not land in the same evidence directory.
    return "auto_issue_fix_" + id_timestamp() + "_" + uuid4().hex[:6]


def default_evidence_dir(workspace_root: Path, run_id: str) -> Path:
    return workspace_root / ".repo-harness" / "auto-issue-fix" / run_id


def default_workdir(workspace_root: Path, run_id: str) -> Path:
    return workspace_root / ".repo-harness" / "auto-issue-fix-workspaces" / run_id


def _public_record(record: AutoIssueFixRunRecord, include_local_paths: bool) -> dict:
    data = asdict(record)
    data["workspace_path"] = portable_path(record.workspace_path, "<workspace>", include_local_paths)
    data["evidence_dir"] = portable_path(record.evidence_dir, "<evidence_dir>", include_local_paths)
    data["workdir"] = portable_path(record.workdir, "<workdir>", include_local_paths) if record.workdir else ""
    data["summary"] = _portable_text(data.get("summary", ""), include_local_paths)
    data["fallback_reason"] = _portable_text(data.get("fallback_reason", ""), include_local_paths)
    data["tests"] = [
        {**item, "command": _portable_text(item.get("command", ""), include_local_paths)}
        for item in data.get("tests", [])
    ]
    data["review_gates"] = [
        {
            **gate,
            "title": _portable_text(gate.get("title", ""), include_local_paths),
            "summary": _portable_text(gate.get("summary", ""), include_local_paths),
            "required_action": _portable_text(gate.get("required_action", ""), include_local_paths),
        }
        for gate in data.get("review_gates", [])
    ]
    if not data.get("metrics"):
        data["metrics"] = build_run_metrics(record)
    return json.loads(redact_text(json.dumps(data, ensure_ascii=False)))


def build_run_metrics(record: AutoIssueFixRunRecord) -> dict:
    tests = record.tests or []
    gates = record.review_gates or ()
    verdict_counts = {verdict: 0 for verdict in AUTO_REVIEW_VERDICTS}
    for gate in gates:
        verdict_counts[gate.verdict] = verdict_counts.get(gate.verdict, 0) + 1
    return {
        "issue_selected": bool(record.repo and record.issue is not None),
        "baseline_status": record.baseline_status or "not_recorded",
        "changed_file_count": len(record.changed_paths or ()),
        "test_command_count": len(tests),
        "tests_passed": sum(1 for item in tests if item.get("status") == "passed"),
        "tests_failed": sum(1 for item in tests if item.get("status") == "failed"),
        "review_gate_verdicts": verdict_counts,
        "final_status": record.status,
        "fallback_reason": record.fallback_reason or "",
    }


def build_preview_review_gates(config: AutoIssueFixConfig, status: str) -> tuple[AutoIssueFixReviewGate, ...]:
    verdict = "pass" if status == "planned" else "block"
    action = (
        "dry-run preview recorded; live execution remains disabled in this version"
        if verdict == "pass"
        else "stop before live GitHub side effects and generate fallback evidence"
    )
    gates = []
    for stage, title, description in AUTO_REVIEW_STAGES:
        gates.append(
            AutoIssueFixReviewGate(
                stage=stage,
                title=title,
                verdict=verdict,
                summary=f"{description} Current mode is {config.mode}; automatic review is {config.auto_review}.",
                required_action=action,
            )
        )
    gates.append(
        AutoIssueFixReviewGate(
            stage="maintainer-trust",
            title="Maintainer trust review",
            verdict=verdict,
            summary="Check public PR-facing text for tool experiment notes before publication.",
            required_action=action,
        )
    )
    return tuple(gates)


def _review_gate_lines(review_gates: list[dict]) -> str:
    if not review_gates:
        return "- (none recorded)"
    return "\n".join(
        f"- `{item.get('stage', '-')}` {item.get('title', '')}: {item.get('verdict', '-')}"
        for item in review_gates
    )


def _changed_path_lines(paths) -> str:
    return "\n".join(f"- `{path}`" for path in paths) or "- (none recorded)"


def _validation_lines(tests) -> str:
    return "\n".join(
        f"- `{item.get('command', '-')}`: {item.get('status', '-')}" for item in tests
    ) or "- (not run)"


def _public_validation_lines(tests) -> str:
    return "\n".join(
        f"- `{_public_pr_text(item.get('command', '-'))}`: {_public_pr_text(item.get('status', '-'))}" for item in tests
    ) or "- (not run)"


def review_gates_block_reason(review_gates: tuple[AutoIssueFixReviewGate, ...], max_review_repairs: int) -> str:
    for gate in review_gates:
        gate.validate()
        if gate.verdict == "block":
            return f"{gate.stage} review gate blocked the run"
        if gate.verdict == "needs_fix" and gate.repair_attempts >= max_review_repairs:
            return f"{gate.stage} review gate exceeded max review repairs"
    return ""


def render_evidence_templates(record: AutoIssueFixRunRecord, include_local_paths: bool = False) -> dict[str, str]:
    public_record = _public_record(record, include_local_paths)
    repo = public_record.get("repo") or "<repo>"
    issue = public_record.get("issue")
    issue_ref = f"#{issue}" if issue is not None else "(auto-discovered)"
    tests = public_record.get("tests") or []
    test_lines = _validation_lines(tests)
    fallback = public_record.get("fallback_reason") or ""
    public_test_lines = _public_validation_lines(tests)
    public_fallback = _public_pr_text(fallback)
    fallback_block = f"\n\n## Fallback\n\nPR creation blocked: {fallback}\n" if fallback else ""
    status = public_record.get("status", "")
    pr_url = public_record.get("pr_url") or ""
    review_gates = public_record.get("review_gates") or []
    review_lines = _review_gate_lines(review_gates)
    metrics = public_record.get("metrics") or {}
    verdicts = metrics.get("review_gate_verdicts") or {}
    metrics_lines = "\n".join(
        [
            f"- Issue selected: `{'yes' if metrics.get('issue_selected') else 'no'}`",
            f"- Baseline status: `{metrics.get('baseline_status', 'not_recorded')}`",
            f"- Changed files: `{metrics.get('changed_file_count', 0)}`",
            f"- Test commands: `{metrics.get('test_command_count', 0)}`",
            f"- Tests passed: `{metrics.get('tests_passed', 0)}`",
            f"- Tests failed: `{metrics.get('tests_failed', 0)}`",
            (
                "- Review verdicts: "
                f"`pass={verdicts.get('pass', 0)}, needs_fix={verdicts.get('needs_fix', 0)}, block={verdicts.get('block', 0)}`"
            ),
        ]
    )

    run_record = f"""# Auto Issue Fix Run Record

## Summary

- Run ID: `{public_record['run_id']}`
- Mode: `{public_record['mode']}`
- Repository: `{repo}`
- Issue: `{issue_ref}`
- Status: `{status}`
- Workspace: `{public_record['workspace_path']}`
- Evidence directory: `{public_record['evidence_dir']}`
- PR URL: `{pr_url or '(none)'}`
- Automatic review: `{public_record.get('auto_review', 'required')}`
- Max review repairs: `{public_record.get('max_review_repairs', 2)}`
- Stage: `{public_record.get('stage') or '(none)'}`
- Branch: `{public_record.get('branch') or '(none)'}`
- Commit: `{public_record.get('commit') or '(none)'}`
- Baseline: `{public_record.get('baseline_status') or '(not recorded)'}`
- Workdir: `{portable_path(public_record.get('workdir') or '', '<workdir>', include_local_paths)}`

## Result

{public_record.get('summary') or '(none)'}

## Metrics Summary

{metrics_lines}

## Automatic Review Gates

{review_lines}

## Tests

{test_lines}
{fallback_block}
## Changed Paths

{_changed_path_lines(public_record.get('changed_paths', ()))}
"""

    if fallback:
        pr_body = f"""# PR-ready fallback

No pull request was created because the run was blocked before publication.

Repository: {repo}
Issue: {issue_ref}
Reason: {public_fallback}
"""
    else:
        pr_body = f"""## Summary

- Provides a focused candidate fix for the linked issue.
- Keeps the change scoped to the files listed in this pull request.

## Related Issue

Closes {issue_ref}

## What Changed

{_changed_path_lines(public_record.get('changed_paths', ()))}

## Validation

{public_test_lines}

## Scope and Risk

- Scope is limited to the files above.
- No unrelated formatting or broad rewrites are intended.
- Please review the patch and validation output carefully before merge.

## Maintainer Notes

- This is a draft pull request for maintainer review.
- Please verify that the patch, test logs, and description match the issue before considering merge.
"""

    formal_summary = f"""# RepoHarness Auto Issue Fix Formal Report Summary

This run is an Auto Issue Fix assisted workflow, not a claim that model output is trusted without governance. RepoHarness coordinates scoped file access, evidence generation, test gates, and PR preparation while preserving auditability.

Start here first: this file is the user-facing summary. Use `pr-body.md` for maintainer-facing PR text, and `run-record.md` plus JSON/review files for audit and debugging.

- Repository: `{repo}`
- Issue: `{issue_ref}`
- Mode: `{public_record['mode']}`
- Status: `{status}`
- Evidence: `{public_record['evidence_dir']}`
- PR: `{pr_url or '(not created)'}`
- Automatic review: `{public_record.get('auto_review', 'required')}`
- Stage: `{public_record.get('stage') or '(none)'}`
- Branch: `{public_record.get('branch') or '(none)'}`
- Changed files: `{metrics.get('changed_file_count', 0)}`
- Tests passed: `{metrics.get('tests_passed', 0)}`
- Tests failed: `{metrics.get('tests_failed', 0)}`

## User-facing summary

- First review this summary and the generated patch.
- Use `pr-body.md` only after you have manually reviewed the diff and validation logs.
- Use `run-record.md` and `reviews/` when you need audit-level details.

## Review Gates

{review_lines}
"""

    rendered = {
        "run-record.md": redact_text(run_record),
        "pr-body.md": redact_text(pr_body),
        "formal-report-summary.md": redact_text(formal_summary),
        "run-record.json": json.dumps(public_record, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
    }
    if fallback:
        rendered["pr-ready-fallback.md"] = redact_text(
            f"""# PR-ready fallback

Auto Issue Fix stopped before creating a pull request.

- Repository: `{repo}`
- Issue: `{issue_ref}`
- Reason: {fallback}
- Evidence: `{public_record['evidence_dir']}`
"""
        )
    return rendered


def write_evidence(record: AutoIssueFixRunRecord, include_local_paths: bool = False) -> dict[str, Path]:
    evidence_dir = Path(record.evidence_dir)
    evidence_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for name, content in render_evidence_templates(record, include_local_paths=include_local_paths).items():
        path = evidence_dir / name
        path.write_text(content, encoding="utf-8")
        written[name] = path
    public_record = _public_record(record, include_local_paths)
    reviews_dir = evidence_dir / "reviews"
    reviews_dir.mkdir(parents=True, exist_ok=True)
    decisions = []
    for gate in public_record.get("review_gates", ()):
        stage = str(gate.get("stage", "unknown"))
        json_path = reviews_dir / f"review-{stage}.json"
        md_path = reviews_dir / f"review-{stage}.md"
        json_path.write_text(json.dumps(gate, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
        md_path.write_text(
            redact_text(
                f"""# {gate.get('title', stage)}

- Stage: `{stage}`
- Verdict: `{gate.get('verdict', '-')}`
- Required action: {gate.get('required_action') or '(none)'}

{gate.get('summary') or ''}
"""
            ),
            encoding="utf-8",
        )
        written[str(json_path.relative_to(evidence_dir))] = json_path
        written[str(md_path.relative_to(evidence_dir))] = md_path
        decisions.append(
            {
                "run_id": public_record.get("run_id"),
                "stage": stage,
                "verdict": gate.get("verdict"),
                "required_action": gate.get("required_action", ""),
            }
        )
    decision_log_path = evidence_dir / "decision-log.jsonl"
    decision_log_path.write_text(
        "".join(json.dumps(item, ensure_ascii=False, sort_keys=True) + "\n" for item in decisions),
        encoding="utf-8",
    )
    written["decision-log.jsonl"] = decision_log_path
    checkpoint_path = evidence_dir / "checkpoint.json"
    checkpoint = {
        "run_id": public_record.get("run_id"),
        "mode": public_record.get("mode"),
        "status": public_record.get("status"),
        "stage": public_record.get("stage") or "",
        "branch": public_record.get("branch") or "",
        "commit": public_record.get("commit") or "",
        "pr_url": public_record.get("pr_url") or "",
        "resume_from": public_record.get("resume_from") or "",
        "next_action": _checkpoint_next_action(public_record),
    }
    checkpoint_path.write_text(json.dumps(checkpoint, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")
    written["checkpoint.json"] = checkpoint_path
    return written


def _checkpoint_next_action(public_record: dict) -> str:
    status = public_record.get("status")
    if status == "completed":
        return "draft PR created; review upstream PR and evidence"
    if status == "paused":
        return "resume after review-gated confirmation"
    if status in {"blocked", "failed"}:
        return "inspect fallback evidence before rerunning"
    if status == "planned":
        return "dry-run preview recorded; rerun without --dry-run for live execution"
    return "inspect evidence and checkpoint before continuing"


def write_evidence_file(evidence_dir: Path, name: str, content: str, include_local_paths: bool = False) -> Path:
    path = evidence_dir / name
    path.parent.mkdir(parents=True, exist_ok=True)
    text = redact_text(str(content))
    if not include_local_paths:
        text = text.replace(str(evidence_dir), "<evidence_dir>")
    path.write_text(text, encoding="utf-8")
    return path


def write_json_evidence(evidence_dir: Path, name: str, payload: dict, include_local_paths: bool = False) -> Path:
    return write_evidence_file(
        evidence_dir,
        name,
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        include_local_paths=include_local_paths,
    )
