import importlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from unittest.mock import patch

from repo_harness.auto_issue_fix import (
    AUTO_REVIEW_STAGES,
    AutoIssueFixConfig,
    AutoIssueFixIssue,
    AutoIssueFixReviewGate,
    AutoIssueFixRunRecord,
    classify_github_error,
    handle_auto_issue_fix_repl_command,
    maintainer_trust_block_reason,
    redact_text,
    render_evidence_templates,
    review_gates_block_reason,
    run_auto_issue_fix,
    run_test_commands,
    write_evidence,
)
from repo_harness.auto_issue_fix.runner import _build_auto_issue_fix_model_client
from repo_harness.auto_issue_fix.workspace import (
    changed_paths,
    git_diff,
    infer_test_commands,
)
from repo_harness.models import FakeModelClient


class FakeGhBackend:
    def __init__(self, fixture_repo, tmp_path):
        self.fixture_repo = Path(fixture_repo)
        self.tmp_path = Path(tmp_path)
        self.created_prs = []
        self.pushed = False
        self.cloned = False

    def issue_view(self, repo, issue):
        return AutoIssueFixIssue(
            repo="example/project",
            number=int(issue),
            title="Fix failing value",
            body="Steps to reproduce: run `python check.py`. Expected exit code 0.",
            url=f"https://github.com/example/project/issues/{issue}",
            labels=("bug", "test"),
        )

    def issue_list(self, repo, limit=20):
        return [self.issue_view(repo, 123)]

    def search_repos(self, query="topic:python sort:stars-desc", limit=10):
        return ["example/project"]

    def default_branch(self, repo):
        return "main"

    def clone(self, repo, destination):
        self.cloned = True
        shutil.copytree(self.fixture_repo, destination)

    def ensure_fork_remote(self, cwd):
        fork = self.tmp_path / "fork.git"
        subprocess.run(["git", "init", "--bare", str(fork)], check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
        subprocess.run(["git", "remote", "add", "fork", str(fork)], cwd=cwd, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")

    def current_user(self):
        return "example-user"

    def create_pr(self, repo, branch, title, body_file, base):
        assert branch == "repo-harness-auto-issue-fix-123"
        assert "--draft" not in title
        assert Path(body_file).is_file()
        body = Path(body_file).read_text(encoding="utf-8")
        for heading in ("## Summary", "## Related Issue", "## What Changed", "## Validation", "## Scope and Risk", "## Maintainer Notes"):
            assert heading in body
        for forbidden in ("AI", "RepoHarness", "MiMo", "experiment", "trace", "benchmark", "dogfood", "generated by"):
            assert forbidden not in body
        self.created_prs.append({"repo": repo, "branch": branch, "title": title, "base": base})
        return "https://github.com/example/project/pull/999"


def make_fixture_repo(tmp_path):
    repo = tmp_path / "fixture"
    repo.mkdir()
    (repo / "README.md").write_text("# Fixture\n", encoding="utf-8")
    (repo / "bug.py").write_text("def value():\n    return 1\n", encoding="utf-8")
    (repo / "check.py").write_text(
        "import sys\nfrom bug import value\nsys.exit(0 if value() == 22 else 1)\n",
        encoding="utf-8",
    )
    subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo, check=True)
    subprocess.run(["git", "add", "."], cwd=repo, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
    subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
    return repo


def fixing_model():
    return FakeModelClient(
        [
            '<tool>{"name":"read_file","args":{"path":"bug.py","start":1,"end":20}}</tool>',
            '<tool name="patch_file" path="bug.py"><old_text>return 1</old_text><new_text>return 22</new_text></tool>',
            "<final>Fixed value().</final>",
        ]
    )


def test_auto_issue_fix_public_facade_delegates_to_focused_modules():
    facade = importlib.import_module("repo_harness.auto_issue_fix")
    runner = importlib.import_module("repo_harness.auto_issue_fix.runner")
    guided_repl = importlib.import_module("repo_harness.auto_issue_fix.guided_repl")

    assert facade.run_auto_issue_fix is runner.run_auto_issue_fix
    assert facade.run_live_auto_issue_fix is runner.run_live_auto_issue_fix
    assert facade.run_auto_issue_fix_argv is guided_repl.run_auto_issue_fix_argv
    assert facade.handle_auto_issue_fix_repl_command is guided_repl.handle_auto_issue_fix_repl_command


def test_auto_issue_fix_command_uses_facade_run_argv_when_patched(capsys):
    import repo_harness.auto_issue_fix as facade

    def fake_run(argv):
        assert argv == ["--repo", "example/project", "--issue", "123", "--dry-run"]
        return 0, "patched command", None

    with patch.object(facade, "run_auto_issue_fix_argv", fake_run):
        code = facade.handle_auto_issue_fix_command(["--repo", "example/project", "--issue", "123", "--dry-run"])

    assert code == 0
    assert "patched command" in capsys.readouterr().out


def test_auto_issue_fix_argv_uses_facade_run_when_patched(tmp_path):
    import repo_harness.auto_issue_fix as facade

    captured = {}

    def fake_run(config):
        captured["config"] = config
        return AutoIssueFixRunRecord(
            run_id="patched",
            mode=config.mode,
            repo=config.repo,
            issue=config.issue,
            workspace_path=str(tmp_path),
            evidence_dir=str(tmp_path / "evidence"),
            status="planned",
            summary="patched",
            tests=[],
        )

    with patch.object(facade, "run_auto_issue_fix", fake_run):
        code, output, record = facade.run_auto_issue_fix_argv(
            ["--repo", "example/project", "--issue", "123", "--dry-run", "--evidence-dir", str(tmp_path / "evidence")]
        )

    assert code == 0
    assert record is not None
    assert captured["config"].repo == "example/project"
    assert "Auto Issue Fix safe preview complete" in output


def test_auto_issue_fix_templates_are_portable_and_redacted_by_default(tmp_path):
    local_workspace = tmp_path / "workspace"
    local_workspace.mkdir()
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_20260525_000000",
        mode="review-gated",
        repo="https://github.com/example/project",
        issue=123,
        workspace_path=str(local_workspace),
        evidence_dir=str(local_workspace / ".repo-harness" / "auto-issue-fix" / "auto_issue_fix_20260525_000000"),
        status="planned",
        summary="Token sk-secret-123 and ghp_secret_456 must not leak.",
        tests=[{"command": "python -m pytest -q", "status": "not_run"}],
    )

    rendered = render_evidence_templates(record, include_local_paths=False)

    assert set(rendered) == {"run-record.md", "pr-body.md", "formal-report-summary.md", "run-record.json"}
    combined = "\n".join(rendered.values())
    assert str(local_workspace) not in combined
    assert "sk-secret-123" not in combined
    assert "ghp_secret_456" not in combined
    assert "<workspace>" in combined
    assert "<evidence_dir>" in combined
    assert "<redacted>" in combined

    payload = json.loads(rendered["run-record.json"])
    assert payload["workspace_path"] == "<workspace>"
    assert payload["evidence_dir"] == "<evidence_dir>"


def test_auto_issue_fix_public_pr_body_is_maintainer_friendly():
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_public_body",
        mode="draft-auto",
        repo="example/project",
        issue=123,
        workspace_path="D:\\Profiles\\TestUser\\repo",
        evidence_dir="D:\\Profiles\\TestUser\\repo\\.repo-harness\\auto-issue-fix\\run",
        status="pr_ready",
        summary="RepoHarness AI experiment should stay out of public PR body.",
        tests=[{"command": "python D:\\Profiles\\TestUser\\repo\\tests\\test_example.py --model mimo-v2.5-pro", "status": "passed"}],
        changed_paths=("src/example.py", "tests/test_example.py"),
    )

    body = render_evidence_templates(record, include_local_paths=False)["pr-body.md"]

    for heading in ("## Summary", "## Related Issue", "## What Changed", "## Validation", "## Scope and Risk", "## Maintainer Notes"):
        assert heading in body
    for forbidden in ("AI", "RepoHarness", "MiMo", "experiment", "trace", "benchmark", "dogfood", "generated by"):
        assert forbidden not in body
    assert "D:\\Profiles" not in body
    assert "TestUser" not in body
    assert "mimo-v2.5-pro" not in body
    assert "Closes #123" in body
    assert "src/example.py" in body


def test_auto_issue_fix_fallback_pr_body_does_not_leak_local_failure_text():
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_public_fallback",
        mode="review-gated",
        repo="example/project",
        issue=123,
        workspace_path="D:\\Profiles\\TestUser\\repo",
        evidence_dir="D:\\Profiles\\TestUser\\repo\\.repo-harness\\auto-issue-fix\\run",
        status="blocked",
        summary="blocked",
        tests=[],
        fallback_reason="RepoHarness model failed in D:\\Profiles\\TestUser\\repo\\.repo-harness\\trace.jsonl",
    )

    body = render_evidence_templates(record, include_local_paths=False)["pr-body.md"]

    assert "D:\\Profiles" not in body
    assert "TestUser" not in body
    assert "RepoHarness" not in body
    assert "model" not in body.lower()
    assert "<path>" in body or "<redacted>" in body


def test_auto_issue_fix_evidence_includes_layered_metrics_summary(tmp_path):
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_metrics",
        mode="draft-auto",
        repo="https://github.com/example/project",
        issue=123,
        workspace_path=str(tmp_path),
        evidence_dir=str(tmp_path / "evidence"),
        status="completed",
        summary="Draft PR created.",
        tests=[{"command": "python -m pytest -q", "status": "passed"}],
        changed_paths=("bug.py", "tests/test_bug.py"),
        baseline_status="failed",
        review_gates=(
            AutoIssueFixReviewGate(
                stage="tests",
                title="测试审查",
                verdict="pass",
                summary="issue-related tests passed",
            ),
        ),
    )

    rendered = render_evidence_templates(record, include_local_paths=False)

    assert "## Metrics Summary" in rendered["run-record.md"]
    assert "- Changed files: `2`" in rendered["run-record.md"]
    assert "- Tests passed: `1`" in rendered["run-record.md"]
    assert '"changed_file_count": 2' in rendered["run-record.json"]
    assert "User-facing summary" in rendered["formal-report-summary.md"]


def test_auto_issue_fix_redaction_covers_common_secret_shapes():
    text = "OPENAI_API_KEY=sk-test123 GITHUB_TOKEN=gho_abc123 cookie=sessionid"

    redacted = redact_text(text)

    assert "sk-test123" not in redacted
    assert "gho_abc123" not in redacted
    assert "sessionid" not in redacted
    assert redacted.count("<redacted>") >= 3


def test_auto_issue_fix_review_stage_labels_are_readable():
    rendered = "\n".join(" ".join(stage) for stage in AUTO_REVIEW_STAGES)

    for expected in (
        "Task Review",
        "Plan Review",
        "Context Review",
        "Diff Review",
        "Test Review",
        "Security Review",
        "PR Readiness Review",
    ):
        assert expected in rendered
    for mojibake_fragment in ("瀹", "鏌", "浠", "纭", "€"):
        assert mojibake_fragment not in rendered


def test_auto_issue_fix_cli_dry_run_writes_standard_evidence_files(tmp_path):
    evidence_dir = tmp_path / "evidence"
    env = dict(os.environ)
    env["PYTHONPATH"] = os.getcwd() + os.pathsep + env.get("PYTHONPATH", "")
    command = [
        sys.executable,
        "-m",
        "repo_harness",
        "auto-issue-fix",
        "--repo",
        "https://github.com/example/project",
        "--issue",
        "123",
        "--evidence-dir",
        str(evidence_dir),
        "--dry-run",
    ]

    completed = subprocess.run(command, cwd=os.getcwd(), env=env, text=True, encoding="utf-8", errors="replace", capture_output=True, timeout=30, check=False)

    assert completed.returncode == 0, completed.stderr
    assert "Auto Issue Fix safe preview complete" in completed.stdout
    for name in ("run-record.md", "pr-body.md", "formal-report-summary.md", "run-record.json"):
        assert (evidence_dir / name).is_file()
    for name in (
        "reviews/review-task.json",
        "reviews/review-plan.json",
        "reviews/review-context.json",
        "reviews/review-diff.json",
        "reviews/review-tests.json",
        "reviews/review-security.json",
        "reviews/review-pr-readiness.json",
        "reviews/review-maintainer-trust.json",
        "decision-log.jsonl",
        "checkpoint.json",
    ):
        assert (evidence_dir / name).is_file()


def test_auto_issue_fix_direct_api_dry_run_writes_standard_evidence_files(tmp_path):
    evidence_dir = tmp_path / "evidence"
    config = AutoIssueFixConfig(
        repo="example/project",
        issue=123,
        dry_run=True,
        evidence_dir=evidence_dir,
    )

    record = run_auto_issue_fix(config)

    assert record.status == "planned"
    for name in (
        "run-record.md",
        "run-record.json",
        "formal-report-summary.md",
        "checkpoint.json",
    ):
        assert (evidence_dir / name).is_file()


def test_auto_issue_fix_draft_auto_requires_explicit_risk_acknowledgement(tmp_path):
    config = AutoIssueFixConfig(
        repo="https://github.com/example/project",
        issue=123,
        mode="draft-auto",
        evidence_dir=tmp_path,
        dry_run=True,
    )

    assert "automatic review gates" in config.risk_notice()
    assert "block verdict" in config.risk_notice()


def test_auto_issue_fix_review_gated_also_records_auto_review_gates(tmp_path):
    config = AutoIssueFixConfig(
        repo="https://github.com/example/project",
        issue=123,
        mode="review-gated",
        evidence_dir=tmp_path,
        dry_run=True,
    )

    record = run_auto_issue_fix(config)

    assert record.auto_review == "required"
    assert [gate.stage for gate in record.review_gates] == [
        "task",
        "plan",
        "context",
        "diff",
        "tests",
        "security",
        "pr-readiness",
        "maintainer-trust",
    ]
    assert {gate.verdict for gate in record.review_gates} == {"pass"}


def test_auto_issue_fix_draft_auto_cannot_disable_auto_review():
    config = AutoIssueFixConfig(
        repo="https://github.com/example/project",
        issue=123,
        mode="draft-auto",
        dry_run=True,
        auto_review="off",
    )

    try:
        config.validate()
    except ValueError as exc:
        assert "auto-review must be required" in str(exc)
    else:
        raise AssertionError("draft-auto must reject disabled automatic review gates")


def test_auto_issue_fix_rejects_negative_review_repair_limit():
    config = AutoIssueFixConfig(
        repo="https://github.com/example/project",
        issue=123,
        dry_run=True,
        max_review_repairs=-1,
    )

    try:
        config.validate()
    except ValueError as exc:
        assert "max-review-repairs" in str(exc)
    else:
        raise AssertionError("negative max_review_repairs should fail validation")


def test_auto_issue_fix_needs_fix_stops_after_max_review_repairs():
    gate = AutoIssueFixReviewGate(
        stage="diff",
        title="Diff 审查",
        verdict="needs_fix",
        summary="Unrelated file changed.",
        required_action="run bounded repair",
        repair_attempts=2,
    )

    assert review_gates_block_reason((gate,), max_review_repairs=2) == "diff review gate exceeded max review repairs"


def test_auto_issue_fix_maintainer_trust_gate_blocks_public_sensitive_terms():
    reason = maintainer_trust_block_reason(
        title="Fix issue",
        body="This was generated by an AI experiment with RepoHarness.",
        commit_message="fix: address issue 123",
        branch="repo-harness-auto-issue-fix-123",
    )

    assert "maintainer trust" in reason


def test_auto_issue_fix_maintainer_trust_gate_blocks_public_secrets_and_paths():
    secret_reason = maintainer_trust_block_reason(
        title="Fix issue",
        body="Safe public body.",
        commit_message="fix with sk-public-secret",
        branch="repo-harness-auto-issue-fix-123",
    )
    path_reason = maintainer_trust_block_reason(
        title="Fix issue",
        body="Safe public body.",
        commit_message="fix from C:\\Users\\TestUser\\repo",
        branch="repo-harness-auto-issue-fix-123",
    )

    assert "maintainer trust" in secret_reason
    assert "maintainer trust" in path_reason


def test_auto_issue_fix_github_block_error_classifier_prevents_retry():
    text = "GraphQL: You have been blocked from the pallets organization"

    classification = classify_github_error(text)

    assert classification == "blocked_or_forbidden"


def test_auto_issue_fix_failed_gate_generates_fallback_without_pr(tmp_path):
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_failed",
        mode="review-gated",
        repo="https://github.com/example/project",
        issue=123,
        workspace_path=str(tmp_path),
        evidence_dir=str(tmp_path / "evidence"),
        status="failed",
        summary="Tests failed; do not create a PR.",
        tests=[{"command": "python -m pytest -q", "status": "failed"}],
        fallback_reason="test gate failed",
        review_gates=(
            AutoIssueFixReviewGate(
                stage="tests",
                title="测试审查",
                verdict="block",
                summary="test gate failed",
                required_action="stop before PR creation",
            ),
        ),
    )

    rendered = render_evidence_templates(record, include_local_paths=False)

    assert "test gate failed" in rendered["run-record.md"]
    assert "PR creation blocked" in rendered["run-record.md"]
    assert "draft PR" not in rendered["pr-body.md"]
    assert "pr-ready-fallback.md" in rendered


def test_auto_issue_fix_block_verdict_writes_review_artifacts_and_fallback(tmp_path):
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_blocked",
        mode="draft-auto",
        repo="https://github.com/example/project",
        issue=123,
        workspace_path=str(tmp_path),
        evidence_dir=str(tmp_path / "evidence"),
        status="blocked",
        summary="Secret scan failed.",
        tests=[],
        fallback_reason="secret gate failed",
        review_gates=(
            AutoIssueFixReviewGate(
                stage="security",
                title="安全审查",
                verdict="block",
                summary="Secret scan failed.",
                required_action="generate fallback evidence",
            ),
        ),
    )

    write_evidence(record, include_local_paths=False)

    evidence_dir = tmp_path / "evidence"
    assert (evidence_dir / "reviews" / "review-security.json").is_file()
    assert (evidence_dir / "reviews" / "review-security.md").is_file()
    assert (evidence_dir / "decision-log.jsonl").is_file()
    assert (evidence_dir / "checkpoint.json").is_file()
    assert (evidence_dir / "pr-ready-fallback.md").is_file()


def test_auto_issue_fix_review_artifacts_redact_gate_paths_and_secrets(tmp_path):
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_redacted_review",
        mode="draft-auto",
        repo="https://github.com/example/project",
        issue=123,
        workspace_path=str(tmp_path),
        evidence_dir=str(tmp_path / "evidence"),
        status="failed",
        summary="Failed.",
        tests=[],
        fallback_reason="failed",
        review_gates=(
            AutoIssueFixReviewGate(
                stage="task",
                title="Task Review",
                verdict="block",
                summary="workdir already exists: C:\\Users\\TestUser\\repo\\.repo-harness\\trace.jsonl",
                required_action="remove token=sk-review-secret before retry",
            ),
        ),
    )

    write_evidence(record, include_local_paths=False)

    review_json = (tmp_path / "evidence" / "reviews" / "review-task.json").read_text(encoding="utf-8")
    review_md = (tmp_path / "evidence" / "reviews" / "review-task.md").read_text(encoding="utf-8")
    assert "C:\\Users" not in review_json
    assert "C:\\Users" not in review_md
    assert "sk-review-secret" not in review_json
    assert "sk-review-secret" not in review_md
    assert "<path>" in review_json
    assert "<redacted>" in review_json


def test_auto_issue_fix_repl_defaults_to_discovery_safe_preview(tmp_path):
    code, output = handle_auto_issue_fix_repl_command("--discover --dry-run", workspace_root=tmp_path)

    assert code == 0
    assert "Auto Issue Fix safe preview complete" in output
    evidence_root = tmp_path / ".repo-harness" / "auto-issue-fix"
    run_dirs = list(evidence_root.glob("auto_issue_fix_*"))
    assert run_dirs, "expected at least one auto_issue_fix_* evidence directory"
    assert (run_dirs[0] / "run-record.json").exists()
    assert (run_dirs[0] / "checkpoint.json").exists()


def test_auto_issue_fix_repl_without_args_is_usage_when_not_interactive(tmp_path):
    code, output = handle_auto_issue_fix_repl_command("", workspace_root=tmp_path)

    assert code == 2
    assert "usage: /auto-issue-fix" in output


def test_auto_issue_fix_guided_repl_builds_review_gated_live_command(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 1, "Auto Issue Fix paused for review-gated confirmation", None

    answers = iter(["", "example/project", "123", "python check.py", "yes"])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 1
    assert captured["argv"] == [
        "--repo",
        "example/project",
        "--issue",
        "123",
        "--mode",
        "review-gated",
        "--workspace-root",
        str(tmp_path),
        "--test-command",
        "python check.py",
        "--confirm-maintainer-access",
    ]
    assert "Auto Issue Fix guided command prepared" in output
    assert "paused for review-gated confirmation" in output


def test_auto_issue_fix_guided_repl_supports_dry_run_choice(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 0, "Auto Issue Fix safe preview complete", None

    answers = iter(["dry-run", "example/project", "123", ""])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 0
    assert "--dry-run" in captured["argv"]
    assert "--test-command" not in captured["argv"]
    assert "safe preview complete" in output


def test_auto_issue_fix_guided_repl_blank_repo_discovers_from_trending(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 0, "Auto Issue Fix safe preview complete", None

    answers = iter(["dry-run", "", ""])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 0
    assert captured["argv"] == [
        "--discover",
        "--source",
        "trending",
        "--criteria",
        "bug,test",
        "--mode",
        "review-gated",
        "--workspace-root",
        str(tmp_path),
        "--dry-run",
    ]
    assert "Auto Issue Fix guided command prepared" in output


def test_auto_issue_fix_guided_repl_blank_issue_discovers_within_repo(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 1, "Auto Issue Fix paused for review-gated confirmation", None

    answers = iter(["", "example/project", "", "python check.py", "yes"])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 1
    assert captured["argv"] == [
        "--discover",
        "--source",
        "repo",
        "--repo",
        "example/project",
        "--criteria",
        "bug,test",
        "--mode",
        "review-gated",
        "--workspace-root",
        str(tmp_path),
        "--test-command",
        "python check.py",
        "--confirm-maintainer-access",
    ]
    assert "paused for review-gated confirmation" in output


def test_auto_issue_fix_guided_repl_supports_draft_auto_choice(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 0, "Auto Issue Fix draft PR created", None

    answers = iter(["draft-auto", "example/project", "123", "", "yes"])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 0
    assert "--mode" in captured["argv"]
    assert captured["argv"][captured["argv"].index("--mode") + 1] == "draft-auto"
    assert "--confirm-maintainer-access" in captured["argv"]
    assert "draft PR created" in output


def test_auto_issue_fix_guided_repl_does_not_confirm_maintainer_access_by_default(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 1, "Auto Issue Fix evidence generated; live execution did not create a PR", None

    answers = iter(["", "example/project", "123", "", ""])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 1
    assert "--confirm-maintainer-access" not in captured["argv"]
    assert "confirm maintainer access" in output.lower()


def test_auto_issue_fix_live_draft_auto_creates_draft_pr_with_fake_backend(tmp_path):
    fixture = make_fixture_repo(tmp_path)
    backend = FakeGhBackend(fixture, tmp_path)
    config = AutoIssueFixConfig(
        repo="example/project",
        issue=123,
        mode="draft-auto",
        evidence_dir=tmp_path / "evidence",
        workdir=tmp_path / "clone",
        dry_run=False,
        test_commands=("python check.py",),
        maintainer_access_confirmed=True,
    )

    record = run_auto_issue_fix(config, model_client=fixing_model(), gh_backend=backend)

    assert record.status == "completed"
    assert record.pr_url == "https://github.com/example/project/pull/999"
    assert record.changed_paths == ("bug.py",)
    assert record.baseline_status == "failed"
    assert (tmp_path / "evidence" / "issue.json").is_file()
    assert (tmp_path / "evidence" / "baseline-repro.log").is_file()
    assert (tmp_path / "evidence" / "fix-run.log").is_file()
    assert (tmp_path / "evidence" / "test-after-fix.log").is_file()
    assert (tmp_path / "evidence" / "git-diff.patch").is_file()
    assert (tmp_path / "evidence" / "pr-url.txt").read_text(encoding="utf-8").strip() == record.pr_url
    assert backend.created_prs


def test_auto_issue_fix_review_gated_non_tty_pauses_before_commit(tmp_path):
    fixture = make_fixture_repo(tmp_path)
    backend = FakeGhBackend(fixture, tmp_path)
    config = AutoIssueFixConfig(
        repo="example/project",
        issue=123,
        mode="review-gated",
        evidence_dir=tmp_path / "evidence",
        workdir=tmp_path / "clone",
        dry_run=False,
        test_commands=("python check.py",),
        maintainer_access_confirmed=True,
    )

    record = run_auto_issue_fix(config, model_client=fixing_model(), gh_backend=backend)

    assert record.status == "paused"
    assert record.stage == "paused"
    assert not backend.created_prs
    assert (tmp_path / "evidence" / "checkpoint.json").is_file()


def test_auto_issue_fix_live_blocks_when_fix_produces_no_diff(tmp_path):
    fixture = make_fixture_repo(tmp_path)
    backend = FakeGhBackend(fixture, tmp_path)
    config = AutoIssueFixConfig(
        repo="example/project",
        issue=123,
        mode="draft-auto",
        evidence_dir=tmp_path / "evidence",
        workdir=tmp_path / "clone",
        dry_run=False,
        test_commands=(),
        maintainer_access_confirmed=True,
    )

    record = run_auto_issue_fix(config, model_client=FakeModelClient(["<final>No change.</final>"]), gh_backend=backend)

    assert record.status == "blocked"
    assert "review gate blocked" in record.fallback_reason
    assert not backend.created_prs


def test_auto_issue_fix_direct_api_block_writes_standard_fallback_evidence(tmp_path):
    fixture = make_fixture_repo(tmp_path)
    backend = FakeGhBackend(fixture, tmp_path)
    config = AutoIssueFixConfig(
        repo="example/project",
        issue=123,
        mode="draft-auto",
        evidence_dir=tmp_path / "evidence",
        workdir=tmp_path / "clone",
        dry_run=False,
        test_commands=(),
        maintainer_access_confirmed=True,
    )

    record = run_auto_issue_fix(config, model_client=FakeModelClient(["<final>No change.</final>"]), gh_backend=backend)

    assert record.status == "blocked"
    for name in (
        "run-record.md",
        "run-record.json",
        "formal-report-summary.md",
        "pr-ready-fallback.md",
        "checkpoint.json",
    ):
        assert (tmp_path / "evidence" / name).is_file()


def test_auto_issue_fix_live_blocks_without_maintainer_access_confirmation(tmp_path):
    fixture = make_fixture_repo(tmp_path)
    backend = FakeGhBackend(fixture, tmp_path)
    config = AutoIssueFixConfig(
        repo="example/project",
        issue=123,
        mode="draft-auto",
        evidence_dir=tmp_path / "evidence",
        workdir=tmp_path / "clone",
        dry_run=False,
        test_commands=("python check.py",),
    )

    model = FakeModelClient(["<final>this should not run</final>"])

    record = run_auto_issue_fix(config, model_client=model, gh_backend=backend)

    assert record.status == "blocked"
    assert record.stage == "maintainer-access-blocked"
    assert "maintainer access" in record.fallback_reason
    assert backend.cloned is False
    assert model.prompts == []
    assert not backend.created_prs
    assert (tmp_path / "evidence" / "pr-ready-fallback.md").is_file()


def test_auto_issue_fix_live_model_client_uses_workspace_provider_config(tmp_path, monkeypatch):
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    subprocess.run(["git", "init"], cwd=workspace, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
    (workspace / ".repo-harness.toml").write_text(
        "\n".join(
            [
                'provider = "chat-completions"',
                "",
                "[providers.chat-completions]",
                'model = "workspace-chat-model"',
                'base_url = "https://workspace.example/v1"',
                'api_key_env = "WORKSPACE_CHAT_API_KEY"',
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    monkeypatch.setenv("WORKSPACE_CHAT_API_KEY", "workspace-secret")

    client = _build_auto_issue_fix_model_client(AutoIssueFixConfig(workspace_root=workspace, repo="x/y", issue=1), workspace)

    assert client.__class__.__name__ == "ChatCompletionsCompatibleModelClient"
    assert client.model == "workspace-chat-model"
    assert client.base_url == "https://workspace.example/v1"


def test_auto_issue_fix_live_model_client_uses_deepseek_registry_defaults(tmp_path, monkeypatch):
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    subprocess.run(["git", "init"], cwd=workspace, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
    (workspace / ".repo-harness.toml").write_text('provider = "deepseek"\n', encoding="utf-8")
    monkeypatch.setenv("DEEPSEEK_API_KEY", "deepseek-secret")

    client = _build_auto_issue_fix_model_client(AutoIssueFixConfig(workspace_root=workspace, repo="x/y", issue=1), workspace)

    assert client.__class__.__name__ == "AnthropicCompatibleModelClient"
    assert client.model == "deepseek-v4-pro"
    assert client.base_url == "https://api.deepseek.com/anthropic"


def test_auto_issue_fix_diff_helpers_include_staged_changes(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
    (repo / "staged.txt").write_text("staged\n", encoding="utf-8")
    subprocess.run(["git", "add", "staged.txt"], cwd=repo, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")

    assert changed_paths(repo) == ("staged.txt",)
    diff = git_diff(repo)
    assert "staged.txt" in diff
    assert "+staged" in diff


def test_auto_issue_fix_diff_helpers_include_untracked_changes(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo, check=True)
    (repo / "README.md").write_text("# Repo\n", encoding="utf-8")
    subprocess.run(["git", "add", "README.md"], cwd=repo, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
    subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace")
    (repo / "new_file.py").write_text("VALUE = 1\n", encoding="utf-8")

    assert changed_paths(repo) == ("new_file.py",)
    diff = git_diff(repo)
    assert "new_file.py" in diff
    assert "+VALUE = 1" in diff


def test_auto_issue_fix_test_logs_are_redacted(tmp_path):
    script = tmp_path / "leak.py"
    script.write_text(
        "print('OPENAI_API_KEY=sk-test-secret')\n"
        "raise SystemExit(1)\n",
        encoding="utf-8",
    )
    log_path = tmp_path / "test.log"

    results = run_test_commands((f"{sys.executable} {script}",), tmp_path, log_path)
    text = log_path.read_text(encoding="utf-8")

    assert results[0]["status"] == "failed"
    assert "sk-test-secret" not in text
    assert "<redacted>" in text


def test_infer_test_commands_python_with_pyproject(tmp_path):
    (tmp_path / "pyproject.toml").write_text("[tool.pytest]\n", encoding="utf-8")
    (tmp_path / "tests").mkdir()
    assert infer_test_commands(tmp_path) == ("python -m pytest -q",)


def test_infer_test_commands_python_with_setup_cfg(tmp_path):
    (tmp_path / "setup.cfg").write_text("[pytest]\n", encoding="utf-8")
    (tmp_path / "test").mkdir()
    assert infer_test_commands(tmp_path) == ("python -m pytest -q",)


def test_infer_test_commands_npm(tmp_path):
    (tmp_path / "package.json").write_text('{"scripts": {"test": "jest"}}\n', encoding="utf-8")
    assert infer_test_commands(tmp_path) == ("npm test",)


def test_infer_test_commands_go(tmp_path):
    (tmp_path / "go.mod").write_text("module example\n", encoding="utf-8")
    assert infer_test_commands(tmp_path) == ("go test ./...",)


def test_infer_test_commands_rust(tmp_path):
    (tmp_path / "Cargo.toml").write_text('[package]\nname = "demo"\n', encoding="utf-8")
    assert infer_test_commands(tmp_path) == ("cargo test",)


def test_infer_test_commands_maven(tmp_path):
    (tmp_path / "pom.xml").write_text("<project></project>\n", encoding="utf-8")
    assert infer_test_commands(tmp_path) == ("mvn test",)


def test_infer_test_commands_gradle(tmp_path):
    (tmp_path / "build.gradle").write_text("apply plugin: 'java'\n", encoding="utf-8")
    assert infer_test_commands(tmp_path) == ("gradle test",)


def test_infer_test_commands_gradle_kotlin(tmp_path):
    (tmp_path / "build.gradle.kts").write_text("plugins { java }\n", encoding="utf-8")
    assert infer_test_commands(tmp_path) == ("gradle test",)


def test_infer_test_commands_dotnet(tmp_path):
    (tmp_path / "App.csproj").write_text("<Project></Project>\n", encoding="utf-8")
    assert infer_test_commands(tmp_path) == ("dotnet test",)


def test_infer_test_commands_ruby(tmp_path):
    (tmp_path / "Gemfile").write_text("source 'https://rubygems.org'\n", encoding="utf-8")
    (tmp_path / "spec").mkdir()
    assert infer_test_commands(tmp_path) == ("bundle exec rspec",)


def test_infer_test_commands_cmake(tmp_path):
    (tmp_path / "CMakeLists.txt").write_text("cmake_minimum_required(VERSION 3.10)\n", encoding="utf-8")
    assert infer_test_commands(tmp_path) == ("ctest --output-on-failure",)


def test_infer_test_commands_unknown_returns_empty(tmp_path):
    (tmp_path / "README.md").write_text("just a readme\n", encoding="utf-8")
    assert infer_test_commands(tmp_path) == ()
