import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from unittest.mock import patch

from repo_harness.auto_issue_fix import (
    AutoIssueFixConfig,
    AutoIssueFixIssue,
    AutoIssueFixReviewGate,
    AutoIssueFixRunRecord,
    classify_github_error,
    handle_auto_issue_fix_repl_command,
    maintainer_trust_block_reason,
    render_evidence_templates,
    review_gates_block_reason,
    run_auto_issue_fix,
    redact_text,
    write_evidence,
)
from repo_harness.models import FakeModelClient


class FakeGhBackend:
    def __init__(self, fixture_repo, tmp_path):
        self.fixture_repo = Path(fixture_repo)
        self.tmp_path = Path(tmp_path)
        self.created_prs = []
        self.pushed = False

    def issue_view(self, repo, issue):
        return AutoIssueFixIssue(
            repo="example/project",
            number=int(issue),
            title="Fix failing value",
            body="Steps to reproduce: run `python check.py`. Expected exit code 0.",
            url=f"https://github.com/example/project/issues/{issue}",
            labels=("bug", "test"),
        )

    def issue_list(self, repo, limit=20):
        return [self.issue_view(repo, 123)]

    def search_repos(self, query="topic:python sort:stars-desc", limit=10):
        return ["example/project"]

    def default_branch(self, repo):
        return "main"

    def clone(self, repo, destination):
        shutil.copytree(self.fixture_repo, destination)

    def ensure_fork_remote(self, cwd):
        fork = self.tmp_path / "fork.git"
        subprocess.run(["git", "init", "--bare", str(fork)], check=True, capture_output=True, text=True)
        subprocess.run(["git", "remote", "add", "fork", str(fork)], cwd=cwd, check=True, capture_output=True, text=True)

    def current_user(self):
        return "example-user"

    def create_pr(self, repo, branch, title, body_file, base):
        assert branch == "repo-harness-auto-issue-fix-123"
        assert "--draft" not in title
        assert Path(body_file).is_file()
        body = Path(body_file).read_text(encoding="utf-8")
        for heading in ("## Summary", "## Related Issue", "## Validation", "## Scope", "## Notes for Maintainers"):
            assert heading in body
        for forbidden in ("AI", "RepoHarness", "MiMo", "experiment", "trace", "benchmark", "dogfood", "generated by"):
            assert forbidden not in body
        self.created_prs.append({"repo": repo, "branch": branch, "title": title, "base": base})
        return "https://github.com/example/project/pull/999"


def make_fixture_repo(tmp_path):
    repo = tmp_path / "fixture"
    repo.mkdir()
    (repo / "README.md").write_text("# Fixture\n", encoding="utf-8")
    (repo / "bug.py").write_text("def value():\n    return 1\n", encoding="utf-8")
    (repo / "check.py").write_text(
        "import sys\nfrom bug import value\nsys.exit(0 if value() == 22 else 1)\n",
        encoding="utf-8",
    )
    subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True, text=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo, check=True)
    subprocess.run(["git", "add", "."], cwd=repo, check=True, capture_output=True, text=True)
    subprocess.run(["git", "commit", "-m", "initial"], cwd=repo, check=True, capture_output=True, text=True)
    return repo


def fixing_model():
    return FakeModelClient(
        [
            '<tool>{"name":"read_file","args":{"path":"bug.py","start":1,"end":20}}</tool>',
            '<tool name="patch_file" path="bug.py"><old_text>return 1</old_text><new_text>return 22</new_text></tool>',
            "<final>Fixed value().</final>",
        ]
    )


def test_auto_issue_fix_templates_are_portable_and_redacted_by_default(tmp_path):
    local_workspace = tmp_path / "workspace"
    local_workspace.mkdir()
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_20260525_000000",
        mode="review-gated",
        repo="https://github.com/example/project",
        issue=123,
        workspace_path=str(local_workspace),
        evidence_dir=str(local_workspace / ".repo-harness" / "auto-issue-fix" / "auto_issue_fix_20260525_000000"),
        status="planned",
        summary="Token sk-secret-123 and ghp_secret_456 must not leak.",
        tests=[{"command": "python -m pytest -q", "status": "not_run"}],
    )

    rendered = render_evidence_templates(record, include_local_paths=False)

    assert set(rendered) == {"run-record.md", "pr-body.md", "formal-report-summary.md", "run-record.json"}
    combined = "\n".join(rendered.values())
    assert str(local_workspace) not in combined
    assert "sk-secret-123" not in combined
    assert "ghp_secret_456" not in combined
    assert "<workspace>" in combined
    assert "<evidence_dir>" in combined
    assert "<redacted>" in combined

    payload = json.loads(rendered["run-record.json"])
    assert payload["workspace_path"] == "<workspace>"
    assert payload["evidence_dir"] == "<evidence_dir>"


def test_auto_issue_fix_public_pr_body_is_maintainer_friendly():
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_public_body",
        mode="draft-auto",
        repo="example/project",
        issue=123,
        workspace_path="<workspace>",
        evidence_dir="<evidence_dir>",
        status="pr_ready",
        summary="RepoHarness AI experiment should stay out of public PR body.",
        tests=[{"command": "python -m pytest -q", "status": "passed"}],
        changed_paths=("src/example.py", "tests/test_example.py"),
    )

    body = render_evidence_templates(record, include_local_paths=False)["pr-body.md"]

    for heading in ("## Summary", "## Related Issue", "## Validation", "## Scope", "## Notes for Maintainers"):
        assert heading in body
    for forbidden in ("AI", "RepoHarness", "MiMo", "experiment", "trace", "benchmark", "dogfood", "generated by"):
        assert forbidden not in body
    assert "Addresses #123" in body
    assert "src/example.py" in body


def test_auto_issue_fix_redaction_covers_common_secret_shapes():
    text = "OPENAI_API_KEY=sk-test123 GITHUB_TOKEN=gho_abc123 cookie=sessionid"

    redacted = redact_text(text)

    assert "sk-test123" not in redacted
    assert "gho_abc123" not in redacted
    assert "sessionid" not in redacted
    assert redacted.count("<redacted>") >= 3


def test_auto_issue_fix_cli_dry_run_writes_standard_evidence_files(tmp_path):
    evidence_dir = tmp_path / "evidence"
    env = dict(os.environ)
    env["PYTHONPATH"] = os.getcwd() + os.pathsep + env.get("PYTHONPATH", "")
    command = [
        sys.executable,
        "-m",
        "repo_harness",
        "auto-issue-fix",
        "--repo",
        "https://github.com/example/project",
        "--issue",
        "123",
        "--evidence-dir",
        str(evidence_dir),
        "--dry-run",
    ]

    completed = subprocess.run(command, cwd=os.getcwd(), env=env, text=True, capture_output=True, timeout=30, check=False)

    assert completed.returncode == 0, completed.stderr
    assert "Auto Issue Fix safe preview complete" in completed.stdout
    for name in ("run-record.md", "pr-body.md", "formal-report-summary.md", "run-record.json"):
        assert (evidence_dir / name).is_file()
    for name in (
        "reviews/review-task.json",
        "reviews/review-plan.json",
        "reviews/review-context.json",
        "reviews/review-diff.json",
        "reviews/review-tests.json",
        "reviews/review-security.json",
        "reviews/review-pr-readiness.json",
        "reviews/review-maintainer-trust.json",
        "decision-log.jsonl",
        "checkpoint.json",
    ):
        assert (evidence_dir / name).is_file()


def test_auto_issue_fix_draft_auto_requires_explicit_risk_acknowledgement(tmp_path):
    config = AutoIssueFixConfig(
        repo="https://github.com/example/project",
        issue=123,
        mode="draft-auto",
        evidence_dir=tmp_path,
        dry_run=True,
    )

    assert "automatic review gates" in config.risk_notice()
    assert "block verdict" in config.risk_notice()


def test_auto_issue_fix_review_gated_also_records_auto_review_gates(tmp_path):
    config = AutoIssueFixConfig(
        repo="https://github.com/example/project",
        issue=123,
        mode="review-gated",
        evidence_dir=tmp_path,
        dry_run=True,
    )

    record = run_auto_issue_fix(config)

    assert record.auto_review == "required"
    assert [gate.stage for gate in record.review_gates] == [
        "task",
        "plan",
        "context",
        "diff",
        "tests",
        "security",
        "pr-readiness",
        "maintainer-trust",
    ]
    assert {gate.verdict for gate in record.review_gates} == {"pass"}


def test_auto_issue_fix_draft_auto_cannot_disable_auto_review():
    config = AutoIssueFixConfig(
        repo="https://github.com/example/project",
        issue=123,
        mode="draft-auto",
        dry_run=True,
        auto_review="off",
    )

    try:
        config.validate()
    except ValueError as exc:
        assert "auto-review must be required" in str(exc)
    else:
        raise AssertionError("draft-auto must reject disabled automatic review gates")


def test_auto_issue_fix_rejects_negative_review_repair_limit():
    config = AutoIssueFixConfig(
        repo="https://github.com/example/project",
        issue=123,
        dry_run=True,
        max_review_repairs=-1,
    )

    try:
        config.validate()
    except ValueError as exc:
        assert "max-review-repairs" in str(exc)
    else:
        raise AssertionError("negative max_review_repairs should fail validation")


def test_auto_issue_fix_needs_fix_stops_after_max_review_repairs():
    gate = AutoIssueFixReviewGate(
        stage="diff",
        title="Diff 审查",
        verdict="needs_fix",
        summary="Unrelated file changed.",
        required_action="run bounded repair",
        repair_attempts=2,
    )

    assert review_gates_block_reason((gate,), max_review_repairs=2) == "diff review gate exceeded max review repairs"


def test_auto_issue_fix_maintainer_trust_gate_blocks_public_sensitive_terms():
    reason = maintainer_trust_block_reason(
        title="Fix issue",
        body="This was generated by an AI experiment with RepoHarness.",
        commit_message="fix: address issue 123",
        branch="repo-harness-auto-issue-fix-123",
    )

    assert "maintainer trust" in reason


def test_auto_issue_fix_github_block_error_classifier_prevents_retry():
    text = "GraphQL: You have been blocked from the pallets organization"

    classification = classify_github_error(text)

    assert classification == "blocked_or_forbidden"


def test_auto_issue_fix_failed_gate_generates_fallback_without_pr(tmp_path):
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_failed",
        mode="review-gated",
        repo="https://github.com/example/project",
        issue=123,
        workspace_path=str(tmp_path),
        evidence_dir=str(tmp_path / "evidence"),
        status="failed",
        summary="Tests failed; do not create a PR.",
        tests=[{"command": "python -m pytest -q", "status": "failed"}],
        fallback_reason="test gate failed",
        review_gates=(
            AutoIssueFixReviewGate(
                stage="tests",
                title="测试审查",
                verdict="block",
                summary="test gate failed",
                required_action="stop before PR creation",
            ),
        ),
    )

    rendered = render_evidence_templates(record, include_local_paths=False)

    assert "test gate failed" in rendered["run-record.md"]
    assert "PR creation blocked" in rendered["run-record.md"]
    assert "draft PR" not in rendered["pr-body.md"]
    assert "pr-ready-fallback.md" in rendered


def test_auto_issue_fix_block_verdict_writes_review_artifacts_and_fallback(tmp_path):
    record = AutoIssueFixRunRecord(
        run_id="auto_issue_fix_blocked",
        mode="draft-auto",
        repo="https://github.com/example/project",
        issue=123,
        workspace_path=str(tmp_path),
        evidence_dir=str(tmp_path / "evidence"),
        status="blocked",
        summary="Secret scan failed.",
        tests=[],
        fallback_reason="secret gate failed",
        review_gates=(
            AutoIssueFixReviewGate(
                stage="security",
                title="安全审查",
                verdict="block",
                summary="Secret scan failed.",
                required_action="generate fallback evidence",
            ),
        ),
    )

    write_evidence(record, include_local_paths=False)

    evidence_dir = tmp_path / "evidence"
    assert (evidence_dir / "reviews" / "review-security.json").is_file()
    assert (evidence_dir / "reviews" / "review-security.md").is_file()
    assert (evidence_dir / "decision-log.jsonl").is_file()
    assert (evidence_dir / "checkpoint.json").is_file()
    assert (evidence_dir / "pr-ready-fallback.md").is_file()


def test_auto_issue_fix_repl_defaults_to_discovery_safe_preview(tmp_path):
    code, output = handle_auto_issue_fix_repl_command("--discover --dry-run", workspace_root=tmp_path)

    assert code == 0
    assert "Auto Issue Fix safe preview complete" in output
    assert list((tmp_path / ".repo-harness" / "auto-issue-fix").glob("auto_issue_fix_*"))


def test_auto_issue_fix_repl_without_args_is_usage_when_not_interactive(tmp_path):
    code, output = handle_auto_issue_fix_repl_command("", workspace_root=tmp_path)

    assert code == 2
    assert "usage: /auto-issue-fix" in output


def test_auto_issue_fix_guided_repl_builds_review_gated_live_command(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 1, "Auto Issue Fix paused for review-gated confirmation", None

    answers = iter(["", "example/project", "123", "python check.py"])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 1
    assert captured["argv"] == [
        "--repo",
        "example/project",
        "--issue",
        "123",
        "--mode",
        "review-gated",
        "--workspace-root",
        str(tmp_path),
        "--test-command",
        "python check.py",
    ]
    assert "Auto Issue Fix guided command prepared" in output
    assert "paused for review-gated confirmation" in output


def test_auto_issue_fix_guided_repl_supports_dry_run_choice(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 0, "Auto Issue Fix safe preview complete", None

    answers = iter(["dry-run", "example/project", "123", ""])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 0
    assert "--dry-run" in captured["argv"]
    assert "--test-command" not in captured["argv"]
    assert "safe preview complete" in output


def test_auto_issue_fix_guided_repl_blank_repo_discovers_from_trending(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 0, "Auto Issue Fix safe preview complete", None

    answers = iter(["dry-run", "", ""])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 0
    assert captured["argv"] == [
        "--discover",
        "--source",
        "trending",
        "--criteria",
        "bug,test",
        "--mode",
        "review-gated",
        "--workspace-root",
        str(tmp_path),
        "--dry-run",
    ]
    assert "Auto Issue Fix guided command prepared" in output


def test_auto_issue_fix_guided_repl_blank_issue_discovers_within_repo(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 1, "Auto Issue Fix paused for review-gated confirmation", None

    answers = iter(["", "example/project", "", "python check.py"])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 1
    assert captured["argv"] == [
        "--discover",
        "--source",
        "repo",
        "--repo",
        "example/project",
        "--criteria",
        "bug,test",
        "--mode",
        "review-gated",
        "--workspace-root",
        str(tmp_path),
        "--test-command",
        "python check.py",
    ]
    assert "paused for review-gated confirmation" in output


def test_auto_issue_fix_guided_repl_supports_draft_auto_choice(tmp_path):
    captured = {}

    def fake_run(argv):
        captured["argv"] = argv
        return 0, "Auto Issue Fix draft PR created", None

    answers = iter(["draft-auto", "example/project", "123", ""])
    with patch("repo_harness.auto_issue_fix.run_auto_issue_fix_argv", fake_run):
        code, output = handle_auto_issue_fix_repl_command(
            "",
            workspace_root=tmp_path,
            interactive=True,
            input_func=lambda _prompt: next(answers),
        )

    assert code == 0
    assert "--mode" in captured["argv"]
    assert captured["argv"][captured["argv"].index("--mode") + 1] == "draft-auto"
    assert "draft PR created" in output


def test_auto_issue_fix_live_draft_auto_creates_draft_pr_with_fake_backend(tmp_path):
    fixture = make_fixture_repo(tmp_path)
    backend = FakeGhBackend(fixture, tmp_path)
    config = AutoIssueFixConfig(
        repo="example/project",
        issue=123,
        mode="draft-auto",
        evidence_dir=tmp_path / "evidence",
        workdir=tmp_path / "clone",
        dry_run=False,
        test_commands=("python check.py",),
    )

    record = run_auto_issue_fix(config, model_client=fixing_model(), gh_backend=backend)

    assert record.status == "completed"
    assert record.pr_url == "https://github.com/example/project/pull/999"
    assert record.changed_paths == ("bug.py",)
    assert record.baseline_status == "failed"
    assert (tmp_path / "evidence" / "issue.json").is_file()
    assert (tmp_path / "evidence" / "baseline-repro.log").is_file()
    assert (tmp_path / "evidence" / "fix-run.log").is_file()
    assert (tmp_path / "evidence" / "test-after-fix.log").is_file()
    assert (tmp_path / "evidence" / "git-diff.patch").is_file()
    assert (tmp_path / "evidence" / "pr-url.txt").read_text(encoding="utf-8").strip() == record.pr_url
    assert backend.created_prs


def test_auto_issue_fix_review_gated_non_tty_pauses_before_commit(tmp_path):
    fixture = make_fixture_repo(tmp_path)
    backend = FakeGhBackend(fixture, tmp_path)
    config = AutoIssueFixConfig(
        repo="example/project",
        issue=123,
        mode="review-gated",
        evidence_dir=tmp_path / "evidence",
        workdir=tmp_path / "clone",
        dry_run=False,
        test_commands=("python check.py",),
    )

    record = run_auto_issue_fix(config, model_client=fixing_model(), gh_backend=backend)

    assert record.status == "paused"
    assert record.stage == "paused"
    assert not backend.created_prs
    assert (tmp_path / "evidence" / "checkpoint.json").is_file()


def test_auto_issue_fix_live_blocks_when_fix_produces_no_diff(tmp_path):
    fixture = make_fixture_repo(tmp_path)
    backend = FakeGhBackend(fixture, tmp_path)
    config = AutoIssueFixConfig(
        repo="example/project",
        issue=123,
        mode="draft-auto",
        evidence_dir=tmp_path / "evidence",
        workdir=tmp_path / "clone",
        dry_run=False,
        test_commands=(),
    )

    record = run_auto_issue_fix(config, model_client=FakeModelClient(["<final>No change.</final>"]), gh_backend=backend)

    assert record.status == "blocked"
    assert "review gate blocked" in record.fallback_reason
    assert not backend.created_prs
