"""Rewrite every `<!-- measure:key -->` figure in the docs from measure.py.

The figures were regenerated by hand each time, which meant they were only as
current as someone's memory of which commit invalidated them. Running this
after a change that moves any measured quantity is the whole maintenance
procedure; tests/test_delivery_figures.py fails if it was not run.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MARKER = re.compile(r"(<!--\s*measure:([a-z_]+)\s*-->\s*\*{0,2})([\d,]+)")

# `<!-- delta:source_lines -->−2,606（−15.2%）` -- the change against origin/main.
# Generated too, because a marked cell beside a hand-written delta is how the
# summary table went arithmetically false twice: the value updated, the
# difference next to it did not.
DELTA = re.compile(r"(<!--\s*delta:([a-z_]+)(:pct)?\s*-->\s*)[−+\-][\d,]+(（[−+\-][\d.]+%）)?")

BASELINE_REF = "origin/main"


def _tracked_markdown():
    listed = subprocess.run(
        ["git", "ls-files", "-z", "*.md"],
        cwd=REPO, capture_output=True, text=True,
        encoding="utf-8", errors="replace", check=True,
    ).stdout
    paths = (REPO / name for name in sorted(listed.split("\0")) if name.strip())
    return [path for path in paths if path.is_file()]


def _measure(ref=None):
    args = [sys.executable, "scripts/measure.py"] + ([ref] if ref else [])
    return json.loads(subprocess.run(
        args, cwd=REPO, capture_output=True, text=True, encoding="utf-8", check=True,
    ).stdout)


def _delta_text(key, with_pct, measured, baseline):
    if key not in measured or key not in baseline:
        return None
    change = measured[key] - baseline[key]
    sign = "+" if change > 0 else "−"
    body = f"{sign}{abs(change):,}"
    if with_pct and baseline[key]:
        body += f"（{sign}{abs(change) / baseline[key] * 100:.1f}%）"
    return body


def main():
    # The report renders deltas with U+2212, which a cp936 console cannot encode.
    # Same class of defect this project documents: the output is UTF-8 and the
    # stream assumes the system locale.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    measured = _measure()
    baseline = _measure(BASELINE_REF)

    changed = 0
    for path in _tracked_markdown():
        text = path.read_text(encoding="utf-8")
        label = path.relative_to(REPO).as_posix()
        updates = []

        def replace(match, updates=updates, label=label):
            prefix, key, old = match.groups()
            if key not in measured:
                return match.group(0)
            new = f"{measured[key]:,}"
            if new != old:
                updates.append(f"  {label}  {key}: {old} -> {new}")
            return prefix + new

        def replace_delta(match, updates=updates, label=label):
            prefix, key, pct, _tail = match.groups()
            new = _delta_text(key, bool(pct), measured, baseline)
            if new is None:
                return match.group(0)
            old = match.group(0)[len(prefix):]
            if new != old:
                updates.append(f"  {label}  Δ{key}: {old} -> {new}")
            return prefix + new

        updated = DELTA.sub(replace_delta, MARKER.sub(replace, text))
        if updated != text:
            path.write_text(updated, encoding="utf-8")
            print("\n".join(updates))
            changed += len(updates)

    print(f"{changed} figure(s) updated" if changed else "all figures already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
