"""Rewrite every `<!-- measure:key -->` figure in the docs from measure.py.

The figures were regenerated by hand each time, which meant they were only as
current as someone's memory of which commit invalidated them. Running this
after a change that moves any measured quantity is the whole maintenance
procedure; tests/test_delivery_figures.py fails if it was not run.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MARKER = re.compile(r"(<!--\s*measure:([a-z_]+)\s*-->\s*\*{0,2})([\d,]+)")


def _tracked_markdown():
    listed = subprocess.run(
        ["git", "ls-files", "-z", "*.md"],
        cwd=REPO, capture_output=True, text=True,
        encoding="utf-8", errors="replace", check=True,
    ).stdout
    paths = (REPO / name for name in sorted(listed.split("\0")) if name.strip())
    return [path for path in paths if path.is_file()]


def main():
    measured = json.loads(subprocess.run(
        [sys.executable, "scripts/measure.py"], cwd=REPO,
        capture_output=True, text=True, encoding="utf-8", check=True,
    ).stdout)

    changed = 0
    for path in _tracked_markdown():
        text = path.read_text(encoding="utf-8")
        label = path.relative_to(REPO).as_posix()
        updates = []

        def replace(match, updates=updates, label=label):
            prefix, key, old = match.groups()
            if key not in measured:
                return match.group(0)
            new = f"{measured[key]:,}"
            if new != old:
                updates.append(f"  {label}  {key}: {old} -> {new}")
            return prefix + new

        updated = MARKER.sub(replace, text)
        if updated != text:
            path.write_text(updated, encoding="utf-8")
            print("\n".join(updates))
            changed += len(updates)

    print(f"{changed} figure(s) updated" if changed else "all figures already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
